/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title AccessList
 * @dev This contract manages a list of addresses with special access.
 * The owner of the contract can grant and revoke access for any address.
 * This can be used as a simple role-based access control mechanism where
 * other contracts can query this list to authorize actions.
 */
contract AccessList is Ownable {
    mapping(address => bool) private _granted;

    /**
     * @dev Emitted when access is granted to an account.
     * @param account The account that was granted access.
     */
    event Granted(address indexed account);

    /**
     * @dev Emitted when access is revoked from an account.
     * @param account The account whose access was revoked.
     */
    event Revoked(address indexed account);

    /**
     * @dev The constructor is empty. The contract deployer is automatically set as the owner.
     */
    constructor() {}

    /**
     * @dev Checks if a given account has been granted access.
     * @param account The address to check.
     * @return bool True if the account has access, false otherwise.
     */
    function check(address account) public view returns (bool) {
        return _granted[account];
    }

    /**
     * @dev Grants access to a specified account.
     * Can only be called by the owner.
     * Reverts if the account is the zero address or already has access.
     * @param account The address to grant access to.
     */
    function grant(address account) public onlyOwner {
        require(account != address(0), "AccessList: cannot grant access to the zero address");
        require(!_granted[account], "AccessList: account already has access");

        _granted[account] = true;
        emit Granted(account);
    }

    /**
     * @dev Revokes access from a specified account.
     * Can only be called by the owner.
     * Reverts if the account is the zero address or does not currently have access.
     * @param account The address to revoke access from.
     */
    function revoke(address account) public onlyOwner {
        require(account != address(0), "AccessList: cannot revoke access from the zero address");
        require(_granted[account], "AccessList: account does not have access");

        // Deleting the entry is more gas-efficient than setting to false
        // and has the same effect for a boolean in a mapping.
        delete _granted[account];
        emit Revoked(account);
    }
}
