/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title BadgeMinter
 * @author Your Name
 * @notice This contract allows an owner to mint unique badges (NFTs) to users.
 * Each badge is an ERC721 token with a unique URI.
 * The contract uses OpenZeppelin's secure and audited components.
 */
contract BadgeMinter is ERC721, ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;

    // Counter to keep track of the next tokenId to be minted.
    Counters.Counter private _tokenIdCounter;

    /**
     * @dev Event emitted when a new badge is minted.
     * @param to The address receiving the new badge.
     * @param tokenId The unique identifier of the new badge.
     * @param tokenURI The metadata URI associated with the new badge.
     */
    event BadgeMinted(address indexed to, uint256 indexed tokenId, string tokenURI);

    /**
     * @dev Initializes the contract, setting the name and symbol for the ERC721 token.
     * The constructor is empty as per requirements, with token details hard-coded.
     * The caller of the constructor will become the initial owner.
     */
    constructor() ERC721("BadgeMinter Badge", "BMB") {
        // The constructor body is intentionally left empty.
        // Ownership is initialized by the Ownable constructor.
    }

    /**
     * @notice Mints a new badge and assigns it to a user.
     * @dev Can only be called by the contract owner.
     * The token ID is auto-incremented.
     * @param user The address that will receive the minted badge.
     * @param uri The URI for the badge's metadata.
     * @return The ID of the newly minted token.
     */
    function mintBadge(address user, string memory uri) public onlyOwner returns (uint256) {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();

        _safeMint(user, tokenId);
        _setTokenURI(tokenId, uri);

        emit BadgeMinted(user, tokenId, uri);

        return tokenId;
    }

    /**
     * @dev See {ERC721-_burn}.
     * This override is required by Solidity due to multiple inheritance.
     */
    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }

    /**
     * @dev See {ERC721-tokenURI}.
     * This override is required by Solidity due to multiple inheritance.
     */
    function tokenURI(uint256 tokenId) public view override(ERC721, ERC721URIStorage) returns (string memory) {
        return super.tokenURI(tokenId);
    }

    /**
     * @dev Base URI for computing {tokenURI}. If set, the resulting URI for each
     * token will be the concatenation of the `_baseURI` and the `tokenId`.
     * The base URI is not used in this contract since `_setTokenURI` is used
     * to set a specific URI for each token, but the function is provided
     * for ERC721 compliance.
     */
    function _baseURI() internal pure override returns (string memory) {
        return "";
    }

    /**
     * @dev See {IERC721-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721URIStorage) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}
