/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Blacklist
 * @dev A contract that maintains a list of blacklisted addresses.
 * The owner of the contract has the authority to add or remove addresses
 * from this list. This can be used by other contracts to restrict
 * certain actions to non-blacklisted addresses.
 * This contract is owned by the deployer.
 */
contract Blacklist is Ownable {
    mapping(address => bool) private _blacklisted;

    /**
     * @dev Emitted when an account is added to the blacklist.
     */
    event Blacklisted(address indexed account);

    /**
     * @dev Emitted when an account is removed from the blacklist.
     */
    event Removed(address indexed account);

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     * The deployer of the contract will be set as the initial owner by
     * the Ownable constructor.
     */
    constructor() {
        // The Ownable constructor is called implicitly, setting the deployer as the owner.
    }

    /**
     * @dev Adds an address to the blacklist.
     * Can only be called by the owner.
     *
     * Requirements:
     * - The `account` cannot be the zero address.
     * - The `account` must not already be blacklisted.
     *
     * Emits a {Blacklisted} event.
     * @param account The address to add to the blacklist.
     */
    function add(address account) public onlyOwner {
        require(account != address(0), "Blacklist: cannot add the zero address");
        require(!_blacklisted[account], "Blacklist: account is already blacklisted");
        
        _blacklisted[account] = true;
        emit Blacklisted(account);
    }

    /**
     * @dev Removes an address from the blacklist.
     * Can only be called by the owner.
     *
     * Requirements:
     * - The `account` must currently be blacklisted.
     *
     * Emits a {Removed} event.
     * @param account The address to remove from the blacklist.
     */
    function remove(address account) public onlyOwner {
        require(_blacklisted[account], "Blacklist: account is not blacklisted");
        
        _blacklisted[account] = false;
        emit Removed(account);
    }

    /**
     * @dev Checks if an address is on the blacklist.
     * @param account The address to check.
     * @return bool True if the address is blacklisted, false otherwise.
     */
    function check(address account) public view returns (bool) {
        return _blacklisted[account];
    }
}
