/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title CouponBook
 * @author Your Name
 * @notice A contract for issuing and redeeming unique, non-transferable coupons.
 *
 * This contract allows a designated owner to issue coupons to users. Each coupon is
 * identified by a unique ID and contains a string code. The user who was issued the
 * coupon is the only one who can redeem it. Once redeemed, a coupon cannot be used again.
 *
 * The contract utilizes OpenZeppelin's Ownable for access control on the `issue`
 * function and Counters for safely generating unique coupon IDs.
 */
contract CouponBook is Ownable {
    using Counters for Counters.Counter;

    /**
     * @dev A counter to generate unique sequential IDs for each coupon.
     */
    Counters.Counter private _couponIds;

    /**
     * @dev Represents a single coupon, containing its owner, a string code,
     * and its redemption status.
     */
    struct Coupon {
        address owner;
        string code;
        bool isRedeemed;
    }

    /**
     * @dev Mapping from a coupon ID to the Coupon struct.
     * The getter for this mapping is public, allowing anyone to view coupon details.
     */
    mapping(uint256 => Coupon) public coupons;

    /**
     * @dev Emitted when a new coupon is successfully issued to a user.
     * @param id The unique ID of the newly issued coupon.
     * @param user The address of the user who receives the coupon.
     * @param code The string code associated with the coupon.
     */
    event Issued(uint256 indexed id, address indexed user, string code);

    /**
     * @dev Emitted when a coupon is successfully redeemed by its owner.
     * @param id The unique ID of the redeemed coupon.
     * @param user The address of the user who redeemed the coupon.
     */
    event Redeemed(uint256 indexed id, address indexed user);

    /**
     * @dev The constructor is empty as per the requirements.
     * The `Ownable` constructor is implicitly called, setting the contract
     * deployer as the initial owner.
     */
    constructor() {
        // This contract has an empty constructor.
    }

    /**
     * @notice Issues a new coupon to a specified user.
     * @dev Can only be called by the contract owner.
     * Generates a new unique ID, creates a new coupon, and stores it.
     * Emits an {Issued} event.
     * @param user The address to which the coupon will be issued.
     * @param code The string code for the new coupon.
     */
    function issue(address user, string memory code) public onlyOwner {
        require(user != address(0), "CouponBook: Cannot issue to the zero address");
        _couponIds.increment();
        uint256 newId = _couponIds.current();

        coupons[newId] = Coupon({
            owner: user,
            code: code,
            isRedeemed: false
        });

        emit Issued(newId, user, code);
    }

    /**
     * @notice Redeems a coupon.
     * @dev Can only be called by the owner of the coupon.
     * The coupon must exist and must not have been previously redeemed.
     * Marks the coupon as redeemed and emits a {Redeemed} event.
     * @param id The unique ID of the coupon to redeem.
     */
    function redeem(uint256 id) public {
        Coupon storage couponToRedeem = coupons[id];

        require(couponToRedeem.owner != address(0), "CouponBook: Coupon does not exist");
        require(couponToRedeem.owner == msg.sender, "CouponBook: Caller is not the owner");
        require(!couponToRedeem.isRedeemed, "CouponBook: Coupon has already been redeemed");

        couponToRedeem.isRedeemed = true;

        emit Redeemed(id, msg.sender);
    }
}
