/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title CrowdFund
 * @dev A contract for creating and managing crowdfunding campaigns.
 * Users can start campaigns with a specific funding goal. Other users can contribute
 * Ether to these campaigns. If a campaign reaches its goal, the creator
 * can withdraw the collected funds.
 */
contract CrowdFund is ReentrancyGuard {
    /**
     * @dev Represents a single crowdfunding campaign.
     * @param creator The address of the campaign creator.
     * @param name A descriptive name for the campaign.
     * @param goal The target funding amount in wei.
     * @param raisedAmount The total amount of Ether raised so far.
     * @param withdrawn A flag indicating if the funds have been withdrawn by the creator.
     */
    struct Campaign {
        address creator;
        string name;
        uint256 goal;
        uint256 raisedAmount;
        bool withdrawn;
    }

    // Mapping from a campaign ID to the Campaign struct.
    mapping(uint256 => Campaign) public campaigns;
    // Mapping to track contributions per user for each campaign.
    mapping(uint256 => mapping(address => uint256)) public contributions;

    // Counter to generate unique campaign IDs, starting from 0.
    uint256 private _nextCampaignId;

    // --- Events ---

    /**
     * @dev Emitted when a new campaign is started.
     * @param id The unique ID of the new campaign.
     * @param creator The address of the campaign creator.
     * @param name The name of the campaign.
     * @param goal The funding goal in wei.
     */
    event Started(uint256 indexed id, address indexed creator, string name, uint256 goal);

    /**
     * @dev Emitted when a contribution is made to a campaign.
     * @param id The ID of the campaign being contributed to.
     * @param contributor The address of the contributor.
     * @param amount The amount contributed in wei.
     */
    event Contributed(uint256 indexed id, address indexed contributor, uint256 amount);

    /**
     * @dev Emitted when the creator withdraws funds from a successful campaign.
     * @param id The ID of the campaign.
     * @param creator The address of the creator withdrawing funds.
     * @param amount The amount withdrawn in wei.
     */
    event Withdrawn(uint256 indexed id, address indexed creator, uint256 amount);

    // --- Custom Errors ---

    error CrowdFund__InvalidGoal();
    error CrowdFund__InvalidAmount();
    error CrowdFund__CampaignDoesNotExist();
    error CrowdFund__NotCampaignCreator();
    error CrowdFund__GoalNotReached();
    error CrowdFund__AlreadyWithdrawn();
    error CrowdFund__NameCannotBeEmpty();
    error CrowdFund__TransferFailed();

    /**
     * @dev Initializes the contract. The constructor is empty as per requirements.
     */
    constructor() {}

    /**
     * @notice Starts a new crowdfunding campaign.
     * @param name The name of the campaign. Must not be empty.
     * @param goal The funding goal in wei. Must be greater than 0.
     */
    function start(string memory name, uint256 goal) public {
        if (goal == 0) revert CrowdFund__InvalidGoal();
        if (bytes(name).length == 0) revert CrowdFund__NameCannotBeEmpty();

        uint256 id = _nextCampaignId;
        campaigns[id] = Campaign({
            creator: msg.sender,
            name: name,
            goal: goal,
            raisedAmount: 0,
            withdrawn: false
        });

        _nextCampaignId++;

        emit Started(id, msg.sender, name, goal);
    }

    /**
     * @notice Contributes Ether to a specific campaign.
     * @dev The sent value (msg.value) is the contribution amount.
     * @param id The ID of the campaign to contribute to.
     */
    function contribute(uint256 id) public payable {
        if (msg.value == 0) revert CrowdFund__InvalidAmount();

        Campaign storage campaign = campaigns[id];
        // A simple check for existence. If creator is address(0), it hasn't been initialized.
        if (campaign.creator == address(0)) revert CrowdFund__CampaignDoesNotExist();
        if (campaign.withdrawn) revert CrowdFund__AlreadyWithdrawn();

        campaign.raisedAmount += msg.value;
        contributions[id][msg.sender] += msg.value;

        emit Contributed(id, msg.sender, msg.value);
    }

    /**
     * @notice Allows the creator of a successful campaign to withdraw the collected funds.
     * @dev A campaign is successful if its raised amount is greater than or equal to its goal.
     *      This function can only be called once per campaign.
     * @param id The ID of the campaign to withdraw funds from.
     */
    function withdraw(uint256 id) public nonReentrant {
        Campaign storage campaign = campaigns[id];
        
        // --- Checks ---
        if (campaign.creator == address(0)) revert CrowdFund__CampaignDoesNotExist();
        if (campaign.creator != msg.sender) revert CrowdFund__NotCampaignCreator();
        if (campaign.raisedAmount < campaign.goal) revert CrowdFund__GoalNotReached();
        if (campaign.withdrawn) revert CrowdFund__AlreadyWithdrawn();

        // --- Effects ---
        campaign.withdrawn = true;
        uint256 amountToWithdraw = campaign.raisedAmount;

        // --- Interaction ---
        (bool success, ) = msg.sender.call{value: amountToWithdraw}("");
        if (!success) revert CrowdFund__TransferFailed();

        emit Withdrawn(id, msg.sender, amountToWithdraw);
    }
}
