/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Address.sol";

/**
 * @title Escrow
 * @dev A simple multi-escrow contract where a buyer can create an escrow, fund it,
 * and then release the funds to a seller. The seller can refund the funds if needed.
 * This contract manages multiple escrows, each identified by a unique ID.
 */
contract Escrow is ReentrancyGuard {
    using Address for address payable;

    /**
     * @dev Represents the state of an escrow.
     * - Created: The escrow is initialized but not yet funded.
     * - Funded: The buyer has sent the required ETH to the contract.
     * - Released: The buyer has released the funds to the seller.
     * - Refunded: The seller has returned the funds to the buyer.
     */
    enum State {
        Created,
        Funded,
        Released,
        Refunded
    }

    /**
     * @dev Stores the details of an individual escrow.
     * @param buyer The party creating and funding the escrow.
     * @param seller The party receiving the funds upon release.
     * @param amount The amount of ETH held in the escrow.
     * @param state The current state of the escrow.
     */
    struct EscrowData {
        address payable buyer;
        address payable seller;
        uint256 amount;
        State state;
    }

    /**
     * @dev Mapping from an escrow ID to its data.
     */
    mapping(uint256 => EscrowData) public escrows;

    // Counter to generate unique escrow IDs.
    uint256 private _nextEscrowId;

    /**
     * @dev Emitted when a new escrow is created.
     * @param escrowId The unique ID of the escrow.
     * @param buyer The address of the buyer.
     * @param seller The address of the seller.
     * @param amount The amount of ETH for the escrow.
     */
    event Created(uint256 indexed escrowId, address indexed buyer, address indexed seller, uint256 amount);

    /**
     * @dev Emitted when an escrow is funded by the buyer.
     * @param escrowId The unique ID of the escrow.
     */
    event Funded(uint256 indexed escrowId);

    /**
     * @dev Emitted when the funds are released to the seller.
     * @param escrowId The unique ID of the escrow.
     */
    event Released(uint256 indexed escrowId);

    /**
     * @dev Emitted when the funds are refunded to the buyer.
     * @param escrowId The unique ID of the escrow.
     */
    event Refunded(uint256 indexed escrowId);

    /**
     * @dev Initializes the contract, setting the first escrow ID to 1.
     * This avoids conflicts with the default zero value in mappings.
     */
    constructor() {
        _nextEscrowId = 1;
    }

    /**
     * @notice Creates a new escrow.
     * @dev The caller (`msg.sender`) is set as the buyer.
     * @param seller The address of the seller who will receive the funds.
     * @param amount The amount of ETH to be held in escrow.
     * @return escrowId The ID of the newly created escrow.
     */
    function create(address seller, uint256 amount) external returns (uint256) {
        require(seller != address(0), "Escrow: seller is the zero address");
        require(seller != msg.sender, "Escrow: seller cannot be the buyer");
        require(amount > 0, "Escrow: amount must be positive");

        uint256 escrowId = _nextEscrowId;
        escrows[escrowId] = EscrowData({
            buyer: payable(msg.sender),
            seller: payable(seller),
            amount: amount,
            state: State.Created
        });

        _nextEscrowId++;

        emit Created(escrowId, msg.sender, seller, amount);
        return escrowId;
    }

    /**
     * @notice Funds a specific escrow.
     * @dev The caller must be the buyer of the escrow and send the exact amount.
     * NOTE: A parameter `escrowId` is used because this contract manages multiple escrows.
     * A parameter-less `fund()` function would be ambiguous.
     * @param escrowId The ID of the escrow to fund.
     */
    function fund(uint256 escrowId) external payable {
        EscrowData storage escrow = escrows[escrowId];

        require(escrow.buyer != address(0), "Escrow: does not exist");
        require(msg.sender == escrow.buyer, "Escrow: only buyer can fund");
        require(escrow.state == State.Created, "Escrow: not in created state");
        require(msg.value == escrow.amount, "Escrow: incorrect fund amount");

        escrow.state = State.Funded;
        emit Funded(escrowId);
    }

    /**
     * @notice Releases the funds to the seller.
     * @dev Can only be called by the buyer when the escrow is funded.
     * NOTE: A parameter `escrowId` is used because this contract manages multiple escrows.
     * A parameter-less `release()` function would be ambiguous.
     * @param escrowId The ID of the escrow to release.
     */
    function release(uint256 escrowId) external nonReentrant {
        EscrowData storage escrow = escrows[escrowId];

        require(escrow.buyer != address(0), "Escrow: does not exist");
        require(msg.sender == escrow.buyer, "Escrow: only buyer can release funds");
        require(escrow.state == State.Funded, "Escrow: not in funded state");

        escrow.state = State.Released;
        escrow.seller.sendValue(escrow.amount);

        emit Released(escrowId);
    }

    /**
     * @notice Refunds the funds back to the buyer.
     * @dev Can only be called by the seller when the escrow is funded.
     * NOTE: A parameter `escrowId` is used because this contract manages multiple escrows.
     * A parameter-less `refund()` function would be ambiguous.
     * @param escrowId The ID of the escrow to refund.
     */
    function refund(uint256 escrowId) external nonReentrant {
        EscrowData storage escrow = escrows[escrowId];

        require(escrow.buyer != address(0), "Escrow: does not exist");
        require(msg.sender == escrow.seller, "Escrow: only seller can refund");
        require(escrow.state == State.Funded, "Escrow: not in funded state");

        escrow.state = State.Refunded;
        escrow.buyer.sendValue(escrow.amount);

        emit Refunded(escrowId);
    }
}
