/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title EventLog
 * @dev A simple contract to log string messages to the blockchain via events.
 * This contract provides a single function `log` which takes a string message
 * and emits a `Logged` event containing that message.
 * It is designed to be minimal, secure, and gas-efficient for its purpose.
 */
contract EventLog {
    /**
     * @dev Emitted when a message is logged via the `log` function.
     * @param message The string message that was logged.
     */
    event Logged(string message);

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     * This allows for simple, argument-free deployment.
     */
    constructor() {
        // This constructor is intentionally left empty.
    }

    /**
     * @dev Logs a string message by emitting a `Logged` event.
     * Reverts if the provided message is an empty string to prevent spamming
     * empty log entries.
     * @param message The string message to log. `calldata` is used for gas efficiency.
     */
    function log(string calldata message) public {
        require(bytes(message).length > 0, "EventLog: Message cannot be empty");
        emit Logged(message);
    }
}
