/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title GiftBox
 * @dev A contract that allows anyone to deposit Ether, but only the owner can
 *      withdraw the entire balance. It acts as a digital gift box or piggy bank.
 *      This contract uses OpenZeppelin's Ownable for access control and
 *      ReentrancyGuard for secure withdrawals.
 */
contract GiftBox is Ownable, ReentrancyGuard {

    /**
     * @dev Emitted when Ether is deposited into the gift box.
     * @param from The address that deposited the Ether.
     * @param amount The amount of Ether deposited, in wei.
     */
    event Deposited(address indexed from, uint256 amount);

    /**
     * @dev Emitted when the owner "opens" the box and withdraws the full balance.
     * @param to The owner's address that received the Ether.
     * @param amount The total amount of Ether withdrawn, in wei.
     */
    event Opened(address indexed to, uint256 amount);

    /**
     * @dev Initializes the contract, setting the deployer as the initial owner.
     * The constructor is intentionally left empty as per requirements.
     * The Ownable constructor is called implicitly, setting the owner to msg.sender.
     */
    constructor() {
        // No arguments required.
    }

    /**
     * @dev Allows any address to deposit Ether into the contract.
     * The deposited amount must be greater than zero.
     */
    function deposit() public payable {
        require(msg.value > 0, "GiftBox: Deposit amount must be greater than zero.");
        emit Deposited(msg.sender, msg.value);
    }

    /**
     * @dev Allows the owner to withdraw the entire Ether balance of the contract.
     * This function is protected against reentrancy attacks using the nonReentrant modifier.
     * The function will revert if the box is empty.
     */
    function open() public onlyOwner nonReentrant {
        uint256 amount = address(this).balance;
        require(amount > 0, "GiftBox: The box is empty.");

        // Securely transfer the entire balance to the owner.
        // Using the .call method is the recommended practice for sending Ether.
        (bool success, ) = owner().call{value: amount}("");
        require(success, "GiftBox: Ether transfer failed.");

        emit Opened(owner(), amount);
    }

    /**
     * @dev The contract needs a receive function to accept Ether sent directly
     * to its address without a function call. This enhances usability.
     */
    receive() external payable {
        if (msg.value > 0) {
            emit Deposited(msg.sender, msg.value);
        }
    }
}
