/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Karma
 * @dev A contract to manage karma points for user addresses.
 * The owner of the contract has the authority to give or take points.
 * This contract is designed to be simple, secure, and gas-efficient.
 */
contract Karma is Ownable {
    /**
     * @dev Mapping from a user's address to their karma point balance.
     * The mapping is public, which automatically creates a getter function `karma(address)`.
     */
    mapping(address => uint256) public karma;

    /**
     * @dev Emitted when karma points are given to a user.
     * @param user The address of the user receiving the points.
     * @param points The number of points given.
     * @param operator The address that initiated the transaction.
     */
    event Given(address indexed user, uint256 points, address indexed operator);

    /**
     * @dev Emitted when karma points are taken from a user.
     * @param user The address of the user losing the points.
     * @param points The number of points taken.
     * @param operator The address that initiated the transaction.
     */
    event Taken(address indexed user, uint256 points, address indexed operator);

    /**
     * @dev The constructor is empty, as per the requirements.
     * The `Ownable` constructor is implicitly called, setting the contract
     * deployer as the initial owner.
     */
    constructor() {
        // The Ownable constructor is called implicitly, setting the deployer as the owner.
    }

    /**
     * @notice Gives a specified number of karma points to a user.
     * @dev Can only be called by the contract owner.
     * Reverts if the `user` address is the zero address.
     * Emits a `Given` event on success.
     * @param user The address of the user to receive points.
     * @param points The amount of points to give.
     */
    function give(address user, uint256 points) external onlyOwner {
        require(user != address(0), "Karma: cannot give to the zero address");
        if (points == 0) {
            return; // No state change, no event needed.
        }

        // Solidity ^0.8.0 provides built-in overflow checks.
        karma[user] += points;

        emit Given(user, points, _msgSender());
    }

    /**
     * @notice Takes a specified number of karma points from a user.
     * @dev Can only be called by the contract owner.
     * Reverts if the `user` address is the zero address.
     * Reverts if the user has insufficient points (to prevent underflow).
     * Emits a `Taken` event on success.
     * @param user The address of the user to take points from.
     * @param points The amount of points to take.
     */
    function take(address user, uint256 points) external onlyOwner {
        require(user != address(0), "Karma: cannot take from the zero address");
        if (points == 0) {
            return; // No state change, no event needed.
        }

        uint256 currentPoints = karma[user];
        require(currentPoints >= points, "Karma: insufficient points");

        // Solidity ^0.8.0 provides built-in underflow checks.
        karma[user] = currentPoints - points;

        emit Taken(user, points, _msgSender());
    }
}
