/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

/**
 * @title KeyValueStore
 * @dev A simple contract to store and retrieve key-value pairs where the key is
 * a bytes32 and the value is a string.
 *
 * This contract is intentionally simple and does not inherit from OpenZeppelin
 * contracts as the requested functionality does not require features like
 * access control or upgradeability.
 */
contract KeyValueStore {
    /**
     * @dev Event emitted when a new entry is set or an existing one is updated.
     * The key is indexed to allow for efficient searching of events.
     */
    event EntrySet(bytes32 indexed key, string value);

    // Mapping from a bytes32 key to a string value.
    mapping(bytes32 => string) private _store;

    /**
     * @dev The constructor is intentionally left empty as per the requirements.
     */
    constructor() {
        // No initialization is required.
    }

    /**
     * @notice Sets a value for a given key.
     * @dev If the key already exists, its value will be updated.
     *      Emits an {EntrySet} event upon successful execution.
     * @param key The key to associate the value with.
     * @param value The string value to store. `calldata` is used for gas efficiency.
     */
    function set(bytes32 key, string calldata value) public {
        _store[key] = value;
        emit EntrySet(key, value);
    }

    /**
     * @notice Retrieves the value associated with a given key.
     * @dev Returns an empty string if the key has not been set.
     * @param key The key to retrieve the value for.
     * @return The string value associated with the key.
     */
    function get(bytes32 key) public view returns (string memory) {
        return _store[key];
    }
}
