/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

/**
 * @title Logger
 * @dev A simple, append-only logging contract.
 * This contract allows any address to write a string message, which is then
 * emitted as an event. This serves as a permanent, on-chain log.
 */
contract Logger {
    /**
     * @dev Emitted when a new message is logged via the `write` function.
     * @param writer The address that called the `write` function.
     * @param text The message that was logged.
     */
    event Written(address indexed writer, string text);

    /**
     * @dev The constructor is intentionally left empty.
     * This contract does not require any initial state configuration upon deployment.
     */
    constructor() {
        // No initialization is needed.
    }

    /**
     * @dev Records a new log entry by emitting a `Written` event.
     * This function is open for anyone to call.
     *
     * @param text The string message to be logged. The message is stored in
     *        calldata and emitted in the event, not stored in contract storage
     *        to save gas.
     */
    function write(string calldata text) public {
        emit Written(msg.sender, text);
    }
}
