/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title LotteryBox
 * @dev A simple, owner-managed lottery contract.
 * Users can enter by sending a fixed amount of Ether. The owner can
 * pick a winner at any time, who will receive the entire prize pool.
 *
 * NOTE: This contract uses a basic on-chain pseudo-random number generator which is
 * NOT secure for production environments with high value at stake, as it can be
 * influenced by miners. For a production-ready lottery, consider using a
 * verifiable random function (VRF) like Chainlink VRF.
 */
contract LotteryBox is Ownable {
    // --- State Variables ---

    address payable[] private s_players;
    uint256 public constant ENTRY_FEE = 0.01 ether;

    // --- Events ---

    /**
     * @dev Emitted when a player successfully enters the lottery.
     * @param player The address of the player who entered.
     */
    event Entered(address indexed player);

    /**
     * @dev Emitted when a winner is picked by the owner.
     * @param winner The address of the player who won the lottery.
     */
    event WinnerPicked(address indexed winner);

    // --- Constructor ---

    /**
     * @dev Initializes the contract, transferring ownership to the deployer.
     * The constructor is empty as per requirements.
     */
    constructor() {
        // The Ownable constructor is called implicitly, setting the owner to msg.sender.
    }

    // --- Public & External Functions ---

    /**
     * @notice Allows a user to enter the lottery.
     * @dev The user must send exactly the ENTRY_FEE amount of Ether.
     * The sender's address is added to the list of players.
     */
    function enter() external payable {
        require(msg.value == ENTRY_FEE, "LotteryBox: Must send the exact entry fee.");
        s_players.push(payable(msg.sender));
        emit Entered(msg.sender);
    }

    /**
     * @notice The owner can pick a winner from the current players.
     * @dev Selects a random winner, transfers the entire contract balance to them,
     * and resets the lottery for the next round.
     * Reverts if there are no players.
     */
    function pickWinner() external onlyOwner {
        require(s_players.length > 0, "LotteryBox: No players have entered.");

        uint256 winnerIndex = _getRandomNumber() % s_players.length;
        address payable winner = s_players[winnerIndex];

        // Reset the players array for the next round.
        // This is done before the external call to follow the
        // Checks-Effects-Interactions pattern and prevent re-entrancy vulnerabilities.
        s_players = new address payable[](0);

        emit WinnerPicked(winner);

        // Transfer the entire prize pool to the winner.
        (bool success, ) = winner.call{value: address(this).balance}("");
        require(success, "LotteryBox: Failed to send prize to the winner.");
    }

    // --- View Functions ---

    /**
     * @notice Gets the list of current players in the lottery.
     * @return An array of addresses of the current players.
     */
    function getPlayers() external view returns (address payable[] memory) {
        return s_players;
    }

    /**
     * @notice Gets the current prize pool amount.
     * @return The total Ether balance held by the contract.
     */
    function getPrizePool() external view returns (uint256) {
        return address(this).balance;
    }

    // --- Private Functions ---

    /**
     * @dev Generates a pseudo-random number based on block properties.
     * @return A pseudo-random uint256.
     * @notice WARNING: Not a secure source of randomness. Susceptible to miner manipulation.
     * Do NOT use in production for high-value applications without a VRF.
     */
    function _getRandomNumber() private view returns (uint256) {
        return uint256(keccak256(abi.encodePacked(
            block.prevrandao, // Unpredictable value from the Beacon Chain
            block.timestamp,
            s_players.length
        )));
    }
}
