/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title Mailbox
 * @notice A simple contract for sending and receiving on-chain messages.
 * @dev This implementation allows users to send messages to any Ethereum address.
 * The inbox for each user is stored as a dynamic array of messages.
 *
 * NOTE: The inbox array for a user can grow indefinitely. Retrieving a very large
 * inbox via the `inbox` function may consume a significant amount of gas,
 * potentially hitting the block gas limit. For production-heavy use cases,
 * a paginated retrieval mechanism would be more robust.
 */
contract Mailbox {
    /**
     * @dev Represents a single message, containing the sender's address and its content.
     */
    struct Message {
        address from;
        string content;
    }

    /**
     * @dev Emitted when a message is successfully sent from one address to another.
     * @param from The indexed address of the message sender.
     * @param to The indexed address of the message recipient.
     * @param message The content of the sent message.
     */
    event Sent(address indexed from, address indexed to, string message);

    // Mapping from a user's address to their inbox, which is an array of Messages.
    // The mapping is private to enforce access through the dedicated `inbox` function.
    mapping(address => Message[]) private _inboxes;

    /**
     * @dev The constructor is intentionally left empty. This allows for simple,
     * argument-free deployment.
     */
    constructor() {
        // No initialization parameters are required.
    }

    /**
     * @notice Sends a message to a specified recipient address.
     * @dev Appends a new `Message` struct to the recipient's inbox array and
     * emits a `Sent` event. The transaction sender (`msg.sender`) is recorded
     * as the `from` address in the message.
     * @param to The address of the recipient.
     * @param _message The message content to be sent.
     */
    function send(address to, string calldata _message) external {
        require(to != address(0), "Mailbox: Cannot send to the zero address");

        _inboxes[to].push(Message({
            from: msg.sender,
            content: _message
        }));

        emit Sent(msg.sender, to, _message);
    }

    /**
     * @notice Retrieves all messages from a specified user's inbox.
     * @dev This is a view function that returns the entire message history for a user.
     * Be cautious when calling this for inboxes with a large number of messages.
     * @param user The address of the user whose inbox is to be retrieved.
     * @return An array of `Message` structs, representing the user's complete inbox.
     */
    function inbox(address user) external view returns (Message[] memory) {
        return _inboxes[user];
    }
}
