/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Membership
 * @author Your Name
 * @notice A simple contract to manage a list of members, controlled by an owner.
 *
 * This contract allows a designated owner to add and remove addresses from a
 * membership list. It uses OpenZeppelin's `Ownable` for access control.
 *
 * Key Features:
 * - Owner can add members via the `join` function.
 * - Owner can remove members via the `leave` function.
 * - Public `isMember` view function to check membership status.
 * - Events `Joined` and `Left` are emitted for on-chain tracking.
 */
contract Membership is Ownable {
    // Mapping from an address to its membership status.
    mapping(address => bool) private _isMember;

    /**
     * @dev Emitted when a new user joins the membership.
     * @param user The address of the user who joined.
     */
    event Joined(address indexed user);

    /**
     * @dev Emitted when a user leaves the membership.
     * @param user The address of the user who left.
     */
    event Left(address indexed user);

    /**
     * @dev The constructor is empty as per requirements.
     * The `Ownable` constructor is implicitly called, setting the contract
     * deployer as the initial owner.
     */
    constructor() {
        // This contract has no constructor arguments.
    }

    /**
     * @notice Allows the owner to add a new member.
     * @dev Reverts if the user is the zero address or is already a member.
     * @param user The address of the user to add to the membership.
     */
    function join(address user) public onlyOwner {
        require(user != address(0), "Membership: user cannot be the zero address");
        require(!_isMember[user], "Membership: user is already a member");

        _isMember[user] = true;
        emit Joined(user);
    }

    /**
     * @notice Allows the owner to remove an existing member.
     * @dev Reverts if the user is not currently a member.
     * @param user The address of the user to remove from the membership.
     */
    function leave(address user) public onlyOwner {
        require(_isMember[user], "Membership: user is not a member");

        _isMember[user] = false;
        emit Left(user);
    }

    /**
     * @notice Checks if a given address is a member.
     * @param user The address to check.
     * @return bool True if the user is a member, false otherwise.
     */
    function isMember(address user) public view returns (bool) {
        return _isMember[user];
    }
}
