/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title Messenger
 * @dev A simple contract that allows users to send messages on-chain.
 * It emits an event for each message sent, allowing off-chain services
 * to listen and react to messages.
 */
contract Messenger {
    /**
     * @dev Emitted when a message is sent from one address to another.
     * @param from The address of the message sender.
     * @param to The address of the message recipient.
     * @param msg The content of the message.
     */
    event Sent(address indexed from, address indexed to, string msg);

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     * No setup is needed during deployment.
     */
    constructor() {
        // Empty constructor
    }

    /**
     * @notice Sends a message to a specified address.
     * @dev This function is public, allowing any address to send a message.
     * It validates that the recipient is not the zero address and emits a `Sent` event.
     * @param to The address to which the message is being sent.
     * @param message The string message to be sent.
     */
    function sendMessage(address to, string memory message) public {
        require(to != address(0), "Messenger: Cannot send to the zero address");
        emit Sent(msg.sender, to, message);
    }
}
