/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title NFTBadge
 * @dev A simple ERC721 contract for creating non-fungible badges.
 * Each badge has a unique token URI for its metadata. Minting is restricted
 * to the contract owner. This contract is built using OpenZeppelin v4.9.x.
 */
contract NFTBadge is ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;

    // Counter to keep track of the next token ID to be minted.
    Counters.Counter private _tokenIdCounter;

    /**
     * @dev Emitted when a new token is minted.
     * @param to The address that received the new token.
     * @param tokenId The ID of the new token.
     * @param uri The URI associated with the new token.
     */
    event Minted(address indexed to, uint256 indexed tokenId, string uri);

    /**
     * @dev Initializes the contract by setting the name and symbol for the token collection.
     * The constructor has no parameters, as required. The owner of the contract
     * is set to the address that deploys it.
     */
    constructor() ERC721("Badge", "BGE") {
        // This constructor is intentionally empty as per the requirements.
    }

    /**
     * @dev Creates a new badge and assigns it to the `to` address.
     * The URI for the token's metadata is set upon minting.
     * Can only be called by the contract owner.
     * @param to The recipient of the new badge.
     * @param uri The metadata URI for the new badge.
     * @return The ID of the newly created token.
     */
    function mint(address to, string memory uri) public onlyOwner returns (uint256) {
        _tokenIdCounter.increment();
        uint256 newItemId = _tokenIdCounter.current();

        _safeMint(to, newItemId);
        _setTokenURI(newItemId, uri);

        emit Minted(to, newItemId, uri);

        return newItemId;
    }
}
