/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Pledge
 * @dev A contract that allows users to pledge Ether, which can only be withdrawn
 * by the contract owner. It uses OpenZeppelin's Ownable for access control.
 * This contract has an empty constructor and adheres to the specified constraints.
 */
contract Pledge is Ownable {
    /**
     * @dev Emitted when a user successfully pledges Ether to the contract.
     * @param pledger The address of the user who made the pledge.
     * @param amount The amount of Ether pledged.
     */
    event Pledged(address indexed pledger, uint256 amount);

    /**
     * @dev Emitted when the owner withdraws Ether from the contract.
     * @param owner The address of the owner who initiated the withdrawal.
     * @param amount The amount of Ether withdrawn.
     */
    event Withdrawn(address indexed owner, uint256 amount);

    /**
     * @dev The constructor is intentionally left empty.
     * The `Ownable` contract's constructor is implicitly called,
     * setting the deployer as the initial owner.
     */
    constructor() {
        // Intentionally empty as per requirements.
    }

    /**
     * @dev Allows any user to send Ether to the contract as a pledge.
     * The amount sent must be greater than zero.
     * Emits a {Pledged} event.
     */
    function pledge() public payable {
        require(msg.value > 0, "Pledge: amount must be greater than zero");
        emit Pledged(msg.sender, msg.value);
    }

    /**
     * @dev Allows the owner to withdraw the entire Ether balance of the contract.
     * The contract balance must be greater than zero to execute the withdrawal.
     * Emits a {Withdrawn} event.
     *
     * Requirements:
     * - The caller must be the owner of the contract.
     */
    function withdraw() public onlyOwner {
        uint256 amount = address(this).balance;
        require(amount > 0, "Pledge: no funds to withdraw");

        address payable recipient = payable(owner());

        // Securely transfer the entire contract balance to the owner.
        // Using .call() is the recommended method for sending Ether.
        (bool success, ) = recipient.call{value: amount}("");
        require(success, "Pledge: failed to withdraw funds");

        emit Withdrawn(recipient, amount);
    }
}
