/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title PointsLedger
 * @author Expert Solidity Engineer
 * @notice A contract for managing a ledger of points for users. The contract owner
 * has exclusive privileges to award and burn points. Points are non-transferable.
 * @dev This contract uses OpenZeppelin's Ownable for access control.
 */
contract PointsLedger is Ownable {
    // Mapping from a user's address to their points balance.
    mapping(address => uint256) private _balances;

    /**
     * @dev Emitted when points are awarded to a user.
     * @param user The address of the user who received the points.
     * @param points The number of points awarded.
     */
    event Awarded(address indexed user, uint256 points);

    /**
     * @dev Emitted when points are burned from a user's balance.
     * @param user The address of the user whose points were burned.
     * @param points The number of points burned.
     */
    event Burned(address indexed user, uint256 points);

    /**
     * @dev Initializes the contract, setting the deploying account as the owner.
     * The constructor is intentionally left empty as per requirements.
     */
    constructor() {
        // The Ownable constructor is called implicitly, setting the owner
        // to the `msg.sender` of the deployment transaction.
    }

    /**
     * @notice Gets the points balance of a specific user.
     * @param user The address of the user to query.
     * @return The current points balance of the user.
     */
    function balance(address user) public view returns (uint256) {
        return _balances[user];
    }

    /**
     * @notice Awards a specified number of points to a user.
     * @dev Can only be called by the contract owner. A non-zero amount of points
     * must be awarded to a non-zero address. Emits an {Awarded} event on success.
     * @param user The address of the user to award points to.
     * @param points The number of points to award.
     */
    function award(address user, uint256 points) public onlyOwner {
        require(user != address(0), "PointsLedger: cannot award to the zero address");
        require(points > 0, "PointsLedger: points to award must be greater than zero");

        // Solidity ^0.8.0 provides built-in overflow checks.
        _balances[user] += points;

        emit Awarded(user, points);
    }

    /**
     * @notice Burns a specified number of points from a user's balance.
     * @dev Can only be called by the contract owner. The user must have a
     * sufficient balance. A non-zero amount of points must be burned from
     * a non-zero address. Emits a {Burned} event on success.
     * @param user The address of the user to burn points from.
     * @param points The number of points to burn.
     */
    function burn(address user, uint256 points) public onlyOwner {
        require(user != address(0), "PointsLedger: cannot burn from the zero address");
        require(points > 0, "PointsLedger: points to burn must be greater than zero");

        uint256 currentBalance = _balances[user];
        require(currentBalance >= points, "PointsLedger: insufficient balance to burn");

        // Solidity ^0.8.0 provides built-in underflow checks.
        _balances[user] = currentBalance - points;

        emit Burned(user, points);
    }
}
