/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title ProposalBox
 * @dev A simple contract for creating and voting on proposals.
 * This contract allows any address to propose a topic and for any address
 * to cast a single vote for or against each proposal.
 */
contract ProposalBox {
    /**
     * @dev Represents a single proposal with its details and vote counts.
     * @param title The description of the proposal.
     * @param proposer The address that submitted the proposal.
     * @param forVotes The number of votes in favor of the proposal.
     * @param againstVotes The number of votes against the proposal.
     */
    struct Proposal {
        string title;
        address proposer;
        uint256 forVotes;
        uint256 againstVotes;
    }

    /**
     * @dev A list of all proposals ever created. The index of the array is the proposal ID.
     */
    Proposal[] public proposals;

    /**
     * @dev A mapping to track if an address has already voted on a specific proposal.
     * mapping(proposalId => mapping(voterAddress => hasVoted))
     */
    mapping(uint256 => mapping(address => bool)) public hasVoted;

    /**
     * @dev Emitted when a new proposal is created.
     * @param id The unique identifier of the new proposal.
     * @param proposer The address of the account that created the proposal.
     * @param title The title of the proposal.
     */
    event Proposed(uint256 indexed id, address indexed proposer, string title);

    /**
     * @dev Emitted when a vote is cast on a proposal.
     * @param id The ID of the proposal being voted on.
     * @param voter The address of the account that voted.
     * @param support The voter's choice (true for 'for', false for 'against').
     */
    event Voted(uint256 indexed id, address indexed voter, bool support);

    /**
     * @dev The constructor is empty as required.
     */
    constructor() {
        // This contract has an empty constructor.
    }

    /**
     * @notice Creates a new proposal.
     * @dev The proposal title cannot be empty. The sender becomes the proposer.
     * @param title The title or description of the proposal.
     */
    function propose(string memory title) public {
        require(bytes(title).length > 0, "ProposalBox: title cannot be empty");

        uint256 id = proposals.length;

        proposals.push(Proposal({
            title: title,
            proposer: msg.sender,
            forVotes: 0,
            againstVotes: 0
        }));

        emit Proposed(id, msg.sender, title);
    }

    /**
     * @notice Casts a vote on a specific proposal.
     * @dev Each address can only vote once per proposal.
     * Reverts if the proposal ID is invalid or if the sender has already voted.
     * @param id The ID of the proposal to vote on.
     * @param support A boolean indicating the vote (true for 'for', false for 'against').
     */
    function vote(uint256 id, bool support) public {
        require(id < proposals.length, "ProposalBox: proposal does not exist");
        require(!hasVoted[id][msg.sender], "ProposalBox: already voted on this proposal");

        hasVoted[id][msg.sender] = true;

        Proposal storage p = proposals[id];
        if (support) {
            p.forVotes++;
        } else {
            p.againstVotes++;
        }

        emit Voted(id, msg.sender, support);
    }

    /**
     * @notice Retrieves the details of a specific proposal.
     * @param id The ID of the proposal.
     * @return title_ The proposal's title.
     * @return proposer_ The address that created the proposal.
     * @return forVotes_ The number of 'for' votes.
     * @return againstVotes_ The number of 'against' votes.
     */
    function getProposal(uint256 id) public view returns (
        string memory title_,
        address proposer_,
        uint256 forVotes_,
        uint256 againstVotes_
    ) {
        require(id < proposals.length, "ProposalBox: proposal does not exist");
        Proposal storage p = proposals[id];
        return (p.title, p.proposer, p.forVotes, p.againstVotes);
    }

    /**
     * @notice Returns the total number of proposals created.
     * @return The count of all proposals.
     */
    function proposalCount() public view returns (uint256) {
        return proposals.length;
    }
}
