/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";

/**
 * @title Compliance and Verification Registry
 * @author Expert Solidity Engineer
 * @notice A smart contract system for managing compliance artifacts, their verification versions, and auditor attestations.
 * It includes role-based access control, reputation tracking, optional auditor staking, and meta-transaction support.
 * @dev This contract uses OpenZeppelin v4.9.x for core functionalities like access control, pausable, and EIP-712.
 */
contract Registry is AccessControl, Pausable, ReentrancyGuard, EIP712 {
    // =============================================================
    //                           Constants & Roles
    // =============================================================

    bytes32 public constant SUBMITTER_ROLE = keccak256("SUBMITTER_ROLE");
    bytes32 public constant AUDITOR_ROLE = keccak256("AUDITOR_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    // =============================================================
    //                           Data Model
    // =============================================================

    enum Status { ACTIVE, REVOKED, SUPERSEDED }

    struct Attestation {
        address auditor;
        bool approved;
        bytes32 noteHash; // SHA-256 hash of a detailed note/report
        uint256 attestedAt;
        uint8 confidenceLevel; // Scale of 1-5
    }

    struct Version {
        bytes32 resultsHash; // SHA-256 hash of the verification results
        string oscalCid; // IPFS CID for OSCAL document
        string profileId; // Identifier for the compliance profile used
        uint256 complianceScore; // 0-100
        uint256 verifiedAt;
        address submitter;
        Status status;
        uint256 gasUsed;
        mapping(address => Attestation) attestations;
        address[] auditorList;
    }

    struct SubmitterReputation {
        uint256 validSubmissions;
        uint256 revokedCount;
    }

    struct AuditorReputation {
        uint256 attestationCount;
        uint256 approvalCount; // Number of attestations where approved = true
    }

    // =============================================================
    //                             State
    // =============================================================

    // Mapping from artifact hash to its array of versions
    mapping(bytes32 => Version[]) public artifacts;

    // Reputation tracking mappings
    mapping(address => SubmitterReputation) public submitterReputation;
    mapping(address => AuditorReputation) public auditorReputation;

    // Optional Staking
    IERC20 public stakingToken;
    uint256 public auditorStakeAmount;
    bool public stakingEnabled;
    mapping(address => uint256) public auditorStakes;

    // EIP712 meta-transaction support
    // solhint-disable-next-line var-name-mixedcase
    bytes32 private constant _SUBMIT_VERIFICATION_TYPEHASH =
        keccak256(
            "SubmitVerificationRequest(bytes32 artifactHash,bytes32 resultsHash,string oscalCid,string profileId,uint256 complianceScore,uint256 nonce)"
        );
    mapping(address => uint256) public nonces;

    // Initializer guard
    bool private _initialized;


    // =============================================================
    //                             Events
    // =============================================================

    event VerificationSubmitted(
        bytes32 indexed artifactHash,
        uint256 indexed versionIndex,
        address indexed submitter,
        bytes32 resultsHash,
        uint256 complianceScore
    );

    event VerificationRevoked(
        bytes32 indexed artifactHash,
        uint256 indexed versionIndex,
        address indexed revoker,
        bytes32 reasonHash
    );

    event AttestationAdded(
        bytes32 indexed artifactHash,
        uint256 indexed versionIndex,
        address indexed auditor,
        bool approved,
        uint8 confidenceLevel
    );

    // Staking Events
    event Staked(address indexed auditor, uint256 amount);
    event Unstaked(address indexed auditor, uint256 amount);
    event Slashed(address indexed auditor, address indexed slashedBy, uint256 amount);
    event StakingConfigured(address indexed token, uint256 amount, bool enabled);


    // =============================================================
    //                           Constructor & Initializer
    // =============================================================

    /**
     * @dev EIP712 constructor sets up the domain separator.
     * The constructor is empty as per requirements. Use `initialize()` for setup.
     */
    constructor() EIP712("ComplianceAndVerificationRegistry", "1") {}

    /**
     * @dev Initializes the contract by setting the initial admin.
     * Can only be called once.
     * @param initialAdmin The address to be granted DEFAULT_ADMIN_ROLE and PAUSER_ROLE.
     */
    function initialize(address initialAdmin) public {
        require(!_initialized, "Registry: already initialized");
        _setupRole(DEFAULT_ADMIN_ROLE, initialAdmin);
        _setupRole(PAUSER_ROLE, initialAdmin);
        _initialized = true;
    }


    // =============================================================
    //                     Core Functions
    // =============================================================

    /**
     * @notice Submits a new verification version for a given artifact.
     * @dev Supersedes any previously active version for the same artifact.
     *      Can only be called by an address with SUBMITTER_ROLE.
     * @param artifactHash The SHA-256 hash of the artifact.
     * @param resultsHash The SHA-256 hash of the detailed verification results.
     * @param oscalCid The IPFS Content ID for the OSCAL document.
     * @param profileId The identifier of the compliance profile used.
     * @param complianceScore The compliance score from 0 to 100.
     */
    function submitVerification(
        bytes32 artifactHash,
        bytes32 resultsHash,
        string calldata oscalCid,
        string calldata profileId,
        uint256 complianceScore
    ) public virtual onlyRole(SUBMITTER_ROLE) whenNotPaused nonReentrant {
        _submitVerification(_msgSender(), artifactHash, resultsHash, oscalCid, profileId, complianceScore);
    }

    /**
     * @notice Revokes the latest version of an artifact.
     * @dev Can only be called by the DEFAULT_ADMIN_ROLE or the original submitter of that version.
     *      The version must be in ACTIVE status.
     * @param artifactHash The artifact to revoke the latest version of.
     * @param reasonHash A SHA-256 hash of the reason for revocation.
     */
    function revokeLatest(bytes32 artifactHash, bytes32 reasonHash) public whenNotPaused nonReentrant {
        uint256 versionCount = artifacts[artifactHash].length;
        require(versionCount > 0, "Registry: No versions for this artifact");

        Version storage latestVersion = artifacts[artifactHash][versionCount - 1];
        require(latestVersion.status == Status.ACTIVE, "Registry: Latest version is not active");

        address submitter = latestVersion.submitter;
        require(
            hasRole(DEFAULT_ADMIN_ROLE, _msgSender()) || submitter == _msgSender(),
            "Registry: Caller cannot revoke"
        );

        latestVersion.status = Status.REVOKED;

        SubmitterReputation storage rep = submitterReputation[submitter];
        if (rep.validSubmissions > 0) { // Should always be true but defensive
            rep.validSubmissions--;
        }
        rep.revokedCount++;

        emit VerificationRevoked(artifactHash, versionCount - 1, _msgSender(), reasonHash);
    }

    /**
     * @notice Submits or updates an attestation for a specific artifact version.
     * @dev Each auditor can only attest once per version, but can update their attestation.
     *      Requires AUDITOR_ROLE and sufficient stake if staking is enabled.
     * @param artifactHash The artifact being attested.
     * @param versionIndex The index of the version to attest.
     * @param approved Whether the auditor approves the verification.
     * @param noteHash A SHA-256 hash of a detailed note or report.
     * @param confidenceLevel The auditor's confidence in the attestation (1-5).
     */
    function attest(
        bytes32 artifactHash,
        uint256 versionIndex,
        bool approved,
        bytes32 noteHash,
        uint8 confidenceLevel
    ) public onlyRole(AUDITOR_ROLE) whenNotPaused nonReentrant {
        require(confidenceLevel >= 1 && confidenceLevel <= 5, "Registry: Confidence level out of bounds (1-5)");
        if (stakingEnabled) {
            require(auditorStakes[_msgSender()] >= auditorStakeAmount, "Registry: Insufficient stake");
        }

        uint256 versionCount = artifacts[artifactHash].length;
        require(versionIndex < versionCount, "Registry: Version index out of bounds");

        Version storage version = artifacts[artifactHash][versionIndex];
        require(version.status == Status.ACTIVE, "Registry: Version is not active");

        Attestation storage attestation = version.attestations[_msgSender()];
        bool isNewAttestation = (attestation.attestedAt == 0);

        _updateAuditorReputation(isNewAttestation, attestation.approved, approved);

        if (isNewAttestation) {
            version.auditorList.push(_msgSender());
            attestation.auditor = _msgSender();
        }

        attestation.approved = approved;
        attestation.noteHash = noteHash;
        attestation.confidenceLevel = confidenceLevel;
        attestation.attestedAt = block.timestamp;
        
        emit AttestationAdded(artifactHash, versionIndex, _msgSender(), approved, confidenceLevel);
    }

    // =============================================================
    //                  Meta-Transaction Functions
    // =============================================================

    struct SubmitVerificationRequest {
        bytes32 artifactHash;
        bytes32 resultsHash;
        string oscalCid;
        string profileId;
        uint256 complianceScore;
        uint256 nonce;
    }
    
    /**
     * @notice Submits a verification via a delegated EIP-712 signature.
     * @dev Allows a relayer to submit on behalf of a user with SUBMITTER_ROLE.
     * @param req The SubmitVerificationRequest struct containing all parameters.
     * @param signature The EIP-712 signature from the submitter.
     */
    function submitVerificationDelegated(
        SubmitVerificationRequest calldata req,
        bytes calldata signature
    ) public whenNotPaused nonReentrant {
        bytes32 structHash = keccak256(abi.encode(
            _SUBMIT_VERIFICATION_TYPEHASH,
            req.artifactHash,
            req.resultsHash,
            keccak256(bytes(req.oscalCid)),
            keccak256(bytes(req.profileId)),
            req.complianceScore,
            req.nonce
        ));
        
        bytes32 digest = _hashTypedDataV4(structHash);
        address signer = ECDSA.recover(digest, signature);

        require(hasRole(SUBMITTER_ROLE, signer), "Registry: Signer lacks SUBMITTER_ROLE");
        require(nonces[signer] == req.nonce, "Registry: Invalid nonce");
        nonces[signer]++;
        
        _submitVerification(signer, req.artifactHash, req.resultsHash, req.oscalCid, req.profileId, req.complianceScore);
    }

    // =============================================================
    //                   Pausable Control Functions
    // =============================================================

    /** @notice Pauses critical contract functions. Requires PAUSER_ROLE. */
    function pause() public onlyRole(PAUSER_ROLE) {
        _pause();
    }

    /** @notice Unpauses the contract. Requires PAUSER_ROLE. */
    function unpause() public onlyRole(PAUSER_ROLE) {
        _unpause();
    }

    // =============================================================
    //                   Staking Functions (Optional)
    // =============================================================

    /** @notice Sets the configuration for auditor staking. Requires DEFAULT_ADMIN_ROLE. */
    function setStakingConfiguration(address token, uint256 amount, bool enabled) public onlyRole(DEFAULT_ADMIN_ROLE) {
        stakingToken = IERC20(token);
        auditorStakeAmount = amount;
        stakingEnabled = enabled;
        emit StakingConfigured(token, amount, enabled);
    }

    /** @notice Allows an auditor to stake tokens. */
    function stake() public whenNotPaused {
        require(stakingEnabled, "Registry: Staking is not enabled");
        require(auditorStakeAmount > 0, "Registry: Stake amount not set");
        
        uint256 currentStake = auditorStakes[_msgSender()];
        uint256 amountToStake = auditorStakeAmount - currentStake;
        require(amountToStake > 0, "Registry: Stake already sufficient");

        auditorStakes[_msgSender()] = auditorStakeAmount;
        require(
            stakingToken.transferFrom(_msgSender(), address(this), amountToStake),
            "Registry: ERC20 transfer failed"
        );
        emit Staked(_msgSender(), amountToStake);
    }

    /** @notice Allows an auditor to withdraw their entire stake. */
    function unstake() public {
        uint256 amount = auditorStakes[_msgSender()];
        require(amount > 0, "Registry: No stake to withdraw");

        auditorStakes[_msgSender()] = 0;
        require(stakingToken.transfer(_msgSender(), amount), "Registry: ERC20 transfer failed");
        emit Unstaked(_msgSender(), amount);
    }

    /**
     * @notice Slashes a portion of an auditor's stake. Requires DEFAULT_ADMIN_ROLE.
     * @dev Slashed funds are sent to the caller (admin).
     */
    function slash(address auditor, uint256 amount) public onlyRole(DEFAULT_ADMIN_ROLE) {
        uint256 currentStake = auditorStakes[auditor];
        require(amount > 0 && amount <= currentStake, "Registry: Invalid slash amount");

        auditorStakes[auditor] = currentStake - amount;
        require(stakingToken.transfer(_msgSender(), amount), "Registry: ERC20 transfer failed");
        emit Slashed(auditor, _msgSender(), amount);
    }

    // =============================================================
    //                        View Functions
    // =============================================================

    /** @notice Gets the number of versions for a given artifact. */
    function getVersionCount(bytes32 artifactHash) public view returns (uint256) {
        return artifacts[artifactHash].length;
    }

    /** @notice Gets the details of a specific artifact version. */
    function getVersion(bytes32 artifactHash, uint256 versionIndex)
        public
        view
        returns (
            bytes32 resultsHash,
            string memory oscalCid,
            string memory profileId,
            uint256 complianceScore,
            uint256 verifiedAt,
            address submitter,
            Status status,
            uint256 gasUsed
        )
    {
        Version storage version = artifacts[artifactHash][versionIndex];
        return (
            version.resultsHash,
            version.oscalCid,
            version.profileId,
            version.complianceScore,
            version.verifiedAt,
            version.submitter,
            version.status,
            version.gasUsed
        );
    }

    /** @notice Gets the list of auditor addresses for a specific version. */
    function getVersionAuditors(bytes32 artifactHash, uint256 versionIndex) public view returns (address[] memory) {
        return artifacts[artifactHash][versionIndex].auditorList;
    }

    /** @notice Gets the details of a specific attestation. */
    function getAttestation(bytes32 artifactHash, uint256 versionIndex, address auditor)
        public
        view
        returns (Attestation memory)
    {
        return artifacts[artifactHash][versionIndex].attestations[auditor];
    }
    
    /** @notice Gets the reputation details for a submitter. */
    function getSubmitterReputation(address submitter) public view returns (SubmitterReputation memory) {
        return submitterReputation[submitter];
    }

    /** @notice Gets the reputation details for an auditor, including calculated approval ratio. */
    function getAuditorReputation(address auditor)
        public
        view
        returns (uint256 attestationCount, uint256 approvalCount, uint256 approvalRatioBps)
    {
        AuditorReputation memory rep = auditorReputation[auditor];
        approvalRatioBps = 0;
        if (rep.attestationCount > 0) {
            approvalRatioBps = (rep.approvalCount * 10000) / rep.attestationCount;
        }
        return (rep.attestationCount, rep.approvalCount, approvalRatioBps);
    }
    
    // =============================================================
    //                        Internal Functions
    // =============================================================
    
    /**
     * @dev Internal logic for submitting a verification. Shared by public and delegated functions.
     */
    function _submitVerification(
        address submitter,
        bytes32 artifactHash,
        bytes32 resultsHash,
        string calldata oscalCid,
        string calldata profileId,
        uint256 complianceScore
    ) internal {
        require(complianceScore <= 100, "Registry: Score cannot exceed 100");
        uint256 gasStart = gasleft();

        Version[] storage versionHistory = artifacts[artifactHash];
        uint256 versionCount = versionHistory.length;
        if (versionCount > 0) {
            Version storage lastVersion = versionHistory[versionCount - 1];
            if (lastVersion.status == Status.ACTIVE) {
                lastVersion.status = Status.SUPERSEDED;
            }
        }

        uint256 gasEnd = gasleft();

        Version storage newVersion = versionHistory.push();
        newVersion.resultsHash = resultsHash;
        newVersion.oscalCid = oscalCid;
        newVersion.profileId = profileId;
        newVersion.complianceScore = complianceScore;
        newVersion.verifiedAt = block.timestamp;
        newVersion.submitter = submitter;
        newVersion.status = Status.ACTIVE;
        newVersion.gasUsed = gasStart - gasEnd; // Approximate gas used for state changes

        submitterReputation[submitter].validSubmissions++;

        emit VerificationSubmitted(artifactHash, versionHistory.length - 1, submitter, resultsHash, complianceScore);
    }
    
    /**
     * @dev Internal logic to update auditor reputation when an attestation is added or changed.
     */
    function _updateAuditorReputation(bool isNew, bool wasApproved, bool isApproved) internal {
        AuditorReputation storage rep = auditorReputation[_msgSender()];
        if (isNew) {
            rep.attestationCount++;
            if (isApproved) {
                rep.approvalCount++;
            }
        } else {
            if (wasApproved && !isApproved) {
                if(rep.approvalCount > 0) rep.approvalCount--;
            } else if (!wasApproved && isApproved) {
                rep.approvalCount++;
            }
        }
    }
}
