/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Reputation
 * @dev A contract to manage reputation scores for addresses.
 * The owner of the contract has the exclusive authority to increase or decrease
 * the reputation score of any address. This provides a centralized and
 * controlled mechanism for reputation management.
 */
contract Reputation is Ownable {
    // Mapping from an address to its reputation score.
    mapping(address => uint256) private _scores;

    /**
     * @dev Emitted when an account's reputation score is increased.
     * @param account The address whose score was increased.
     * @param amount The amount by which the score was increased.
     * @param newScore The new total score of the account after the increase.
     */
    event Increased(address indexed account, uint256 amount, uint256 newScore);

    /**
     * @dev Emitted when an account's reputation score is decreased.
     * @param account The address whose score was decreased.
     * @param amount The amount by which the score was decreased.
     * @param newScore The new total score of the account after the decrease.
     */
    event Decreased(address indexed account, uint256 amount, uint256 newScore);

    /**
     * @dev Initializes the contract, transferring ownership to the deployer.
     * The constructor is empty as per the requirements. The Ownable constructor
     * is called implicitly, setting the owner to msg.sender.
     */
    constructor() {
        // No arguments required for deployment.
    }

    /**
     * @dev Returns the current reputation score of a given address.
     * @param account The address to query the score for.
     * @return The reputation score of the account.
     */
    function score(address account) public view returns (uint256) {
        return _scores[account];
    }

    /**
     * @dev Increases the reputation score of a given address.
     * Can only be called by the contract owner.
     * Emits an {Increased} event upon successful execution.
     * Reverts on arithmetic overflow.
     * @param account The address whose score to increase.
     * @param amount The non-zero amount to increase the score by.
     */
    function increase(address account, uint256 amount) public onlyOwner {
        require(amount > 0, "Reputation: increase amount must be greater than zero");
        uint256 currentScore = _scores[account];
        uint256 newScore = currentScore + amount;
        _scores[account] = newScore;

        emit Increased(account, amount, newScore);
    }

    /**
     * @dev Decreases the reputation score of a given address.
     * Can only be called by the contract owner.
     * The score cannot be decreased below zero.
     * Emits a {Decreased} event upon successful execution.
     * @param account The address whose score to decrease.
     * @param amount The non-zero amount to decrease the score by.
     */
    function decrease(address account, uint256 amount) public onlyOwner {
        require(amount > 0, "Reputation: decrease amount must be greater than zero");
        uint256 currentScore = _scores[account];
        require(currentScore >= amount, "Reputation: decrease amount exceeds score");
        uint256 newScore = currentScore - amount;
        _scores[account] = newScore;

        emit Decreased(account, amount, newScore);
    }
}
