/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title Scheduler
 * @dev A contract for scheduling and canceling time-based tasks.
 * Each task is associated with the address that created it, and only that
 * address has the authority to cancel it.
 */
contract Scheduler {
    /**
     * @dev Represents a scheduled task.
     * @param id The unique identifier of the task.
     * @param task A description of the task.
     * @param time The UNIX timestamp when the task is meant to be executed.
     * @param scheduler The address that scheduled the task.
     * @param isActive A flag indicating if the task is active or has been canceled.
     */
    struct Task {
        uint256 id;
        string task;
        uint256 time;
        address scheduler;
        bool isActive;
    }

    /**
     * @dev Emitted when a new task is scheduled.
     * @param id The unique ID of the task.
     * @param scheduler The address that scheduled the task.
     * @param task The description of the task.
     * @param time The scheduled execution timestamp.
     */
    event Scheduled(uint256 indexed id, address indexed scheduler, string task, uint256 time);

    /**
     * @dev Emitted when a task is canceled.
     * @param id The unique ID of the canceled task.
     * @param canceller The address that canceled the task.
     */
    event Canceled(uint256 indexed id, address indexed canceller);

    // Mapping from a task ID to the Task struct.
    mapping(uint256 => Task) public tasks;

    // A counter to generate unique task IDs, starting from 1.
    // Id 0 is reserved to indicate a non-existent task.
    uint256 private _nextTaskId = 1;

    /**
     * @dev The constructor is empty as per the requirements.
     */
    constructor() {
        // This contract has an empty constructor.
    }

    /**
     * @notice Schedules a new task.
     * @param task A string describing the task.
     * @param time The future UNIX timestamp for the task's execution.
     * @return id The ID of the newly created task.
     */
    function schedule(string calldata task, uint256 time) external returns (uint256 id) {
        require(time > block.timestamp, "Scheduler: Time must be in the future");
        require(bytes(task).length > 0, "Scheduler: Task description cannot be empty");

        id = _nextTaskId;
        tasks[id] = Task({
            id: id,
            task: task,
            time: time,
            scheduler: msg.sender,
            isActive: true
        });

        // Safely increment for the next task ID.
        // With solc ^0.8.0, this will revert on overflow.
        _nextTaskId++;

        emit Scheduled(id, msg.sender, task, time);
    }

    /**
     * @notice Cancels a previously scheduled task.
     * @dev Only the original scheduler of the task can cancel it.
     * @param id The ID of the task to cancel.
     */
    function cancel(uint256 id) external {
        Task storage taskToCancel = tasks[id];

        require(taskToCancel.id != 0, "Scheduler: Task does not exist");
        require(taskToCancel.isActive, "Scheduler: Task is already canceled");
        require(taskToCancel.scheduler == msg.sender, "Scheduler: Caller is not the task scheduler");

        taskToCancel.isActive = false;

        emit Canceled(id, msg.sender);
    }
}
