/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title SimpleStore
 * @dev A basic contract to store and retrieve a single uint256 value.
 * This contract adheres to the specified constraints, including an empty constructor
 * and specific function signatures. It does not require OpenZeppelin libraries
 * as its functionality is self-contained and simple.
 */
contract SimpleStore {
    uint256 private _value;

    /**
     * @dev Emitted when a new value is stored via the set function.
     * @param newValue The new value that was set.
     */
    event ValueSet(uint256 newValue);

    /**
     * @dev The constructor is intentionally left empty as per the requirements.
     */
    constructor() {
        // This constructor is intentionally empty.
    }

    /**
     * @dev Sets a new value for the stored number.
     * Emits a {ValueSet} event.
     * @param value The new uint256 value to store.
     */
    function set(uint256 value) public {
        _value = value;
        emit ValueSet(value);
    }

    /**
     * @dev Retrieves the currently stored value.
     * @return The uint256 value.
     */
    function get() public view returns (uint256) {
        return _value;
    }
}
