/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title SimpleToken
 * @dev An ERC20 token with a fixed name and symbol, and a minting function
 *      restricted to the contract owner.
 *      This contract uses OpenZeppelin v4.9.x for its base ERC20 and Ownable implementations.
 */
contract SimpleToken is ERC20, Ownable {
    /**
     * @dev Emitted when new tokens are created by the owner.
     * @param to The address that received the newly minted tokens.
     * @param amount The quantity of tokens minted.
     */
    event Minted(address indexed to, uint256 amount);

    /**
     * @dev Initializes the contract, setting the token name to "SimpleToken" and
     *      symbol to "STK". The deployer of the contract is automatically set as the owner.
     *      The constructor has an empty body as per requirements.
     */
    constructor() ERC20("SimpleToken", "STK") {
        // The constructor body is intentionally empty.
        // The owner is set by the Ownable constructor.
    }

    /**
     * @dev Creates `amount` new tokens and assigns them to the `to` address.
     *      This function can only be called by the contract owner.
     *      Upon successful minting, it emits a {Minted} event.
     * @param to The address that will receive the minted tokens.
     * @param amount The amount of tokens to mint.
     */
    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
        emit Minted(to, amount);
    }
}
