/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title SimpleNFTMinter
 * @dev A simple ERC721 non-fungible token contract with a fixed name and symbol.
 * The contract owner can mint new tokens with a specified URI.
 * This contract uses OpenZeppelin v4.9.x contracts.
 */
contract SimpleNFTMinter is ERC721, ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;

    // Counter to keep track of the next token ID to be minted.
    Counters.Counter private _tokenIdCounter;

    /**
     * @dev Event emitted when a new token is minted.
     * @param to The address that received the NFT.
     * @param tokenId The ID of the minted token.
     * @param uri The URI associated with the token's metadata.
     */
    event Minted(address indexed to, uint256 indexed tokenId, string uri);

    /**
     * @dev Initializes the contract, setting the name to 'TestNFT' and symbol to 'TNFT'.
     * The constructor is empty as per requirements, and values are hard-coded.
     */
    constructor() ERC721("TestNFT", "TNFT") {
        // The constructor body is intentionally left empty.
    }

    /**
     * @dev Mints a new token and assigns it to the `to` address, with a specific URI.
     * Can only be called by the contract owner.
     * Emits a {Minted} event.
     * @param to The address to mint the new token to.
     * @param uri The URI for the new token's metadata.
     */
    function mint(address to, string memory uri) public onlyOwner {
        _tokenIdCounter.increment();
        uint256 newItemId = _tokenIdCounter.current();
        
        _safeMint(to, newItemId);
        _setTokenURI(newItemId, uri);

        emit Minted(to, newItemId, uri);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    /**
     * @dev See {ERC721-tokenURI}.
     * This override is required because both ERC721 and ERC721URIStorage implement it.
     */
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    /**
     * @dev See {ERC721-_burn}.
     * This override is required because both ERC721 and ERC721URIStorage implement it.
     */
    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }
}
