/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title SimpleRewards
 * @author Your Name
 * @notice A simple contract for managing a loyalty points system.
 * @dev This contract allows a designated owner to add points to user accounts and redeem them.
 *         It uses OpenZeppelin's Ownable for access control.
 */
contract SimpleRewards is Ownable {
    /**
     * @dev A mapping from user addresses to their point balances.
     */
    mapping(address => uint256) public points;

    /**
     * @dev Emitted when points are added to a user's account.
     * @param user The user whose points were increased.
     * @param pointsAdded The number of points that were added.
     * @param newTotalPoints The new total point balance for the user.
     */
    event PointsAdded(address indexed user, uint256 pointsAdded, uint256 newTotalPoints);

    /**
     * @dev Emitted when points are redeemed from a user's account.
     * @param user The user whose points were redeemed.
     * @param pointsRedeemed The number of points that were redeemed.
     * @param remainingPoints The remaining point balance for the user.
     */
    event Redeemed(address indexed user, uint256 pointsRedeemed, uint256 remainingPoints);

    /**
     * @dev The constructor is intentionally left empty. The deployer becomes the owner.
     */
    constructor() {}

    /**
     * @notice Adds a specified number of points to a user's balance.
     * @dev Can only be called by the contract owner.
     *      Requires that the user address is not the zero address and points to add are greater than zero.
     * @param user The address of the user to receive points.
     * @param pointsToAdd The amount of points to add.
     */
    function addPoints(address user, uint256 pointsToAdd) public onlyOwner {
        require(user != address(0), "SimpleRewards: Cannot add points to the zero address");
        require(pointsToAdd > 0, "SimpleRewards: Points to add must be greater than zero");

        uint256 currentPoints = points[user];
        uint256 newTotalPoints = currentPoints + pointsToAdd;
        points[user] = newTotalPoints;

        emit PointsAdded(user, pointsToAdd, newTotalPoints);
    }

    /**
     * @notice Redeems a specified number of points from a user's balance.
     * @dev Can only be called by the contract owner.
     *      Requires that the user has sufficient points to cover the redemption.
     * @param user The address of the user from whom to redeem points.
     * @param pointsToRedeem The amount of points to redeem.
     */
    function redeem(address user, uint256 pointsToRedeem) public onlyOwner {
        require(pointsToRedeem > 0, "SimpleRewards: Points to redeem must be greater than zero");
        
        uint256 currentPoints = points[user];
        require(currentPoints >= pointsToRedeem, "SimpleRewards: Insufficient points for redemption");

        uint256 remainingPoints = currentPoints - pointsToRedeem;
        points[user] = remainingPoints;

        emit Redeemed(user, pointsToRedeem, remainingPoints);
    }
}
