/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title SimpleAuction
 * @dev A simple auction contract where a beneficiary can start an auction.
 * Bidders can place bids, and the highest bidder wins. The previous highest
 * bidder is refunded immediately upon a new higher bid. The beneficiary

 * can finalize the auction after it ends to receive the funds.
 * This contract uses an initializer function `start` instead of a constructor
 * to set auction parameters.
 */
contract SimpleAuction is ReentrancyGuard {
    /// @notice The address that will receive the funds from the auction.
    address public beneficiary;
    /// @notice The timestamp when the auction officially ends.
    uint256 public auctionEndTime;
    /// @notice The minimum bid required for the first bid.
    uint256 public minBid;

    /// @notice The address of the current highest bidder.
    address public highestBidder;
    /// @notice The amount of the current highest bid.
    uint256 public highestBid;

    /// @notice Flag to indicate if the auction has been started.
    bool public started;
    /// @notice Flag to indicate if the auction has been finalized.
    bool public finalized;

    /**
     * @dev Emitted when the auction is started.
     * @param beneficiary The address that will receive the auction proceeds.
     * @param minBid The minimum bid amount for the first bid.
     * @param endTime The timestamp when the auction will end.
     */
    event Started(address indexed beneficiary, uint256 minBid, uint256 endTime);

    /**
     * @dev Emitted when a new bid is placed.
     * @param bidder The address of the bidder.
     * @param amount The amount of the bid.
     */
    event BidPlaced(address indexed bidder, uint256 amount);

    /**
     * @dev Emitted when the auction is finalized.
     * @param winner The address of the winning bidder.
     * @param amount The winning bid amount.
     */
    event Finalized(address indexed winner, uint256 amount);

    /**
     * @dev Throws if the auction has not been started.
     */
    modifier onlyAfterStart() {
        require(started, "Auction not started");
        _;
    }

    /**
     * @dev Throws if the auction has already ended.
     */
    modifier onlyBeforeEnd() {
        require(block.timestamp < auctionEndTime, "Auction already ended");
        _;
    }

    /**
     * @dev Throws if the auction has not yet ended.
     */
    modifier onlyAfterEnd() {
        require(block.timestamp >= auctionEndTime, "Auction not yet ended");
        _;
    }

    /**
     * @dev Throws if the auction has already been finalized.
     */
    modifier notFinalized() {
        require(!finalized, "Auction already finalized");
        _;
    }

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     * The auction must be initialized via the `start` function.
     */
    constructor() {}

    /**
     * @notice Starts the auction. Can only be called once.
     * @dev The caller of this function becomes the beneficiary.
     * @param _minBid The minimum bid required for the first bid. Must be greater than 0.
     * @param _duration The duration of the auction in seconds. Must be greater than 0.
     */
    function start(uint256 _minBid, uint256 _duration) external {
        require(!started, "Auction already started");
        require(_duration > 0, "Duration must be positive");
        require(_minBid > 0, "Minimum bid must be positive");

        started = true;
        beneficiary = msg.sender;
        minBid = _minBid;
        auctionEndTime = block.timestamp + _duration;

        emit Started(beneficiary, minBid, auctionEndTime);
    }

    /**
     * @notice Places a bid on the auction.
     * @dev The bid amount (`msg.value`) must be greater than the current highest bid.
     * The first bid must be greater than or equal to the minimum bid.
     * The previous highest bidder is refunded their bid amount.
     * Reverts if the auction is not active or if the bid is too low.
     */
    function bid() external payable onlyAfterStart onlyBeforeEnd nonReentrant {
        require(msg.value > highestBid, "Bid not high enough");
        if (highestBid == 0) {
            require(msg.value >= minBid, "First bid must be at least the minimum bid");
        }

        if (highestBidder != address(0)) {
            // Refund the previous highest bidder.
            (bool success, ) = highestBidder.call{value: highestBid}("");
            require(success, "Refund to previous bidder failed");
        }

        highestBidder = msg.sender;
        highestBid = msg.value;

        emit BidPlaced(msg.sender, msg.value);
    }

    /**
     * @notice Finalizes the auction after it has ended.
     * @dev Transfers the highest bid to the beneficiary. Can only be called once,
     * after the auction duration has passed.
     */
    function finalize() external onlyAfterStart onlyAfterEnd notFinalized nonReentrant {
        finalized = true;

        if (highestBidder == address(0)) {
            // No bids were placed, auction ends without a winner.
            emit Finalized(address(0), 0);
            return;
        }
        
        // Transfer the highest bid to the beneficiary.
        (bool success, ) = beneficiary.call{value: highestBid}("");
        require(success, "Transfer to beneficiary failed");

        emit Finalized(highestBidder, highestBid);
    }
}
