/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title Survey
 * @dev A contract for creating, responding to, and closing simple surveys.
 * Each survey is created by an address, and only that address can close it.
 * Anyone can respond to a survey as long as it is open.
 */
contract Survey {
    // --- Structs ---

    /**
     * @dev Represents a single survey.
     * @param id The unique identifier for the survey.
     * @param question The text of the survey question.
     * @param creator The address that created the survey.
     * @param isOpen A flag indicating if the survey is open for responses.
     */
    struct SurveyItem {
        uint256 id;
        string question;
        address creator;
        bool isOpen;
    }

    /**
     * @dev Represents a single response to a survey.
     * @param respondent The address that submitted the response.
     * @param answer The text of the response.
     */
    struct Response {
        address respondent;
        string answer;
    }

    // --- State Variables ---

    uint256 private _nextSurveyId;
    mapping(uint256 => SurveyItem) public surveys;
    mapping(uint256 => Response[]) public surveyResponses;

    // --- Events ---

    /**
     * @dev Emitted when a new survey is created.
     * @param id The unique identifier of the survey.
     * @param creator The address that created the survey.
     * @param question The survey question.
     */
    event Created(uint256 indexed id, address indexed creator, string question);

    /**
     * @dev Emitted when a response is submitted to a survey.
     * @param id The unique identifier of the survey.
     * @param respondent The address that submitted the response.
     * @param answer The content of the response.
     */
    event Responded(uint256 indexed id, address indexed respondent, string answer);

    /**
     * @dev Emitted when a survey is closed.
     * @param id The unique identifier of the survey.
     * @param closer The address that closed the survey (the creator).
     */
    event Closed(uint256 indexed id, address indexed closer);

    // --- Errors ---

    error SurveyNotFound(uint256 id);
    error SurveyNotOpen(uint256 id);
    error SurveyAlreadyClosed(uint256 id);
    error NotSurveyCreator();
    error EmptyInput();

    // --- Constructor ---

    /**
     * @dev Initializes the contract. The constructor is empty as required.
     * The first survey ID will be 1.
     */
    constructor() {
        _nextSurveyId = 1;
    }

    // --- External Functions ---

    /**
     * @dev Creates a new survey.
     * @param question The survey question. Must not be empty.
     * @return newSurveyId The ID of the newly created survey.
     */
    function create(string calldata question) external returns (uint256 newSurveyId) {
        if (bytes(question).length == 0) {
            revert EmptyInput();
        }

        newSurveyId = _nextSurveyId;
        surveys[newSurveyId] = SurveyItem({
            id: newSurveyId,
            question: question,
            creator: msg.sender,
            isOpen: true
        });

        // Safe increment; will not overflow in any realistic scenario.
        unchecked {
            _nextSurveyId++;
        }

        emit Created(newSurveyId, msg.sender, question);
    }

    /**
     * @dev Submits a response to an open survey.
     * @param id The ID of the survey to respond to.
     * @param answer The response. Must not be empty.
     */
    function respond(uint256 id, string calldata answer) external {
        if (bytes(answer).length == 0) {
            revert EmptyInput();
        }

        SurveyItem storage survey = surveys[id];
        if (survey.id == 0) {
            revert SurveyNotFound(id);
        }
        if (!survey.isOpen) {
            revert SurveyNotOpen(id);
        }

        surveyResponses[id].push(Response({
            respondent: msg.sender,
            answer: answer
        }));

        emit Responded(id, msg.sender, answer);
    }

    /**
     * @dev Closes a survey, preventing any further responses.
     * Only the original creator of the survey can close it.
     * @param id The ID of the survey to close.
     */
    function close(uint256 id) external {
        SurveyItem storage survey = surveys[id];

        if (survey.id == 0) {
            revert SurveyNotFound(id);
        }
        if (msg.sender != survey.creator) {
            revert NotSurveyCreator();
        }
        if (!survey.isOpen) {
            revert SurveyAlreadyClosed(id);
        }

        survey.isOpen = false;

        emit Closed(id, msg.sender);
    }
}
