/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title SurveyBox
 * @dev A contract for creating and voting on simple Yes/No surveys.
 * Users can create surveys, vote on them, and the creator can close a survey.
 */
contract SurveyBox {
    using Counters for Counters.Counter;

    // A counter to assign a unique ID to each new survey.
    Counters.Counter private _surveyIds;

    /**
     * @dev Enum for vote choices to improve readability.
     * No = 0, Yes = 1.
     */
    enum VoteChoice { No, Yes }

    /**
     * @dev Represents a single survey.
     * @param creator The address that created the survey.
     * @param question The question posed by the survey.
     * @param yesVotes The total number of 'Yes' votes.
     * @param noVotes The total number of 'No' votes.
     * @param isOpen A flag indicating if the survey is currently open for voting.
     */
    struct Survey {
        address creator;
        string question;
        uint256 yesVotes;
        uint256 noVotes;
        bool isOpen;
    }

    // Mapping from survey ID to the Survey struct.
    mapping(uint256 => Survey) public surveys;

    // Mapping to track which addresses have voted on which surveys to prevent double voting.
    // surveyId => voterAddress => hasVoted
    mapping(uint256 => mapping(address => bool)) public hasVoted;

    // --- Events ---

    /**
     * @dev Emitted when a new survey is created.
     * @param surveyId The unique ID of the new survey.
     * @param creator The address that created the survey.
     * @param question The question for the survey.
     */
    event Created(uint256 indexed surveyId, address indexed creator, string question);

    /**
     * @dev Emitted when an address votes on a survey.
     * @param surveyId The ID of the survey being voted on.
     * @param voter The address that cast the vote.
     * @param choice The choice made by the voter (0 for No, 1 for Yes).
     */
    event Voted(uint256 indexed surveyId, address indexed voter, uint8 choice);

    /**
     * @dev Emitted when a survey is closed.
     * @param surveyId The ID of the survey being closed.
     * @param closer The address that closed the survey (the creator).
     */
    event Closed(uint256 indexed surveyId, address indexed closer);

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     */
    constructor() {
        // No arguments are passed to the constructor.
    }

    /**
     * @dev Creates a new survey with the given question.
     * @param _question The question for the new survey.
     * @return The ID of the newly created survey.
     */
    function createSurvey(string memory _question) public returns (uint256) {
        _surveyIds.increment();
        uint256 newSurveyId = _surveyIds.current();

        surveys[newSurveyId] = Survey({
            creator: msg.sender,
            question: _question,
            yesVotes: 0,
            noVotes: 0,
            isOpen: true
        });

        emit Created(newSurveyId, msg.sender, _question);
        return newSurveyId;
    }

    /**
     * @dev Casts a vote on an existing, open survey.
     * A user can only vote once per survey.
     * @param _id The ID of the survey to vote on.
     * @param _choice The vote choice (0 for No, 1 for Yes).
     */
    function vote(uint256 _id, uint8 _choice) public {
        Survey storage currentSurvey = surveys[_id];

        require(currentSurvey.creator != address(0), "SurveyBox: Survey does not exist");
        require(currentSurvey.isOpen, "SurveyBox: Survey is closed");
        require(!hasVoted[_id][msg.sender], "SurveyBox: Already voted");
        require(
            _choice == uint8(VoteChoice.No) || _choice == uint8(VoteChoice.Yes),
            "SurveyBox: Invalid choice"
        );

        hasVoted[_id][msg.sender] = true;

        if (_choice == uint8(VoteChoice.Yes)) {
            currentSurvey.yesVotes++;
        } else {
            currentSurvey.noVotes++;
        }

        emit Voted(_id, msg.sender, _choice);
    }

    /**
     * @dev Closes a survey, preventing any further votes.
     * Only the creator of the survey can close it.
     * @param _id The ID of the survey to close.
     */
    function close(uint256 _id) public {
        Survey storage currentSurvey = surveys[_id];

        require(currentSurvey.creator != address(0), "SurveyBox: Survey does not exist");
        require(msg.sender == currentSurvey.creator, "SurveyBox: Not the creator");
        require(currentSurvey.isOpen, "SurveyBox: Survey already closed");

        currentSurvey.isOpen = false;

        emit Closed(_id, msg.sender);
    }
}
