/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

/**
 * @title TaskList
 * @dev A simple smart contract to manage a list of tasks.
 * Users can add tasks and mark them as complete. The task ID corresponds
 * to its index in the `tasks` array.
 */
contract TaskList {

    /**
     * @dev Represents a single task in the list.
     * @param id The unique identifier of the task.
     * @param description The textual description of the task.
     * @param isCompleted A flag indicating whether the task has been completed.
     */
    struct Task {
        uint256 id;
        string description;
        bool isCompleted;
    }

    /**
     * @dev Array to store all tasks. The array index serves as the task ID.
     * The `public` visibility keyword creates a getter function for this array,
     * allowing anyone to query a task by its ID.
     */
    Task[] public tasks;

    /**
     * @dev Emitted when a new task is added.
     * @param id The ID of the newly added task.
     * @param description The description of the task.
     */
    event Added(uint256 indexed id, string description);

    /**
     * @dev Emitted when a task is marked as complete.
     * @param id The ID of the completed task.
     */
    event Completed(uint256 indexed id);

    /**
     * @dev The constructor is empty as per the requirements.
     */
    constructor() {
        // No initialization is required for this contract.
    }

    /**
     * @notice Adds a new task to the list.
     * @dev The task ID is assigned automatically based on the current number of tasks.
     * @param _task The description of the task to be added.
     */
    function add(string memory _task) public {
        uint256 newTaskId = tasks.length;
        tasks.push(Task({
            id: newTaskId,
            description: _task,
            isCompleted: false
        }));
        
        emit Added(newTaskId, _task);
    }

    /**
     * @notice Marks a task as complete.
     * @dev Reverts if the task ID is invalid or if the task is already completed.
     * @param _id The ID of the task to complete.
     */
    function complete(uint256 _id) public {
        require(_id < tasks.length, "TaskList: Task does not exist");
        
        Task storage taskToComplete = tasks[_id];
        
        require(!taskToComplete.isCompleted, "TaskList: Task already completed");

        taskToComplete.isCompleted = true;
        
        emit Completed(_id);
    }
}
