/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title Timelock
 * @dev A contract that allows users to lock Ether for a specified period of time.
 * This contract uses a simple counter for lock IDs and ensures that only the
 * owner of a lock can withdraw their funds after the timelock period has expired.
 * It leverages OpenZeppelin's ReentrancyGuard to prevent re-entrancy attacks
 * on the unlock function.
 */
contract Timelock is ReentrancyGuard {
    /**
     * @dev Represents a single lock of Ether.
     * @param owner The address of the user who locked the funds.
     * @param amount The amount of Ether locked, in wei.
     * @param until The UNIX timestamp until which the funds are locked.
     * @param active A flag to indicate if the lock is still active (not yet unlocked).
     */
    struct Lock {
        address owner;
        uint256 amount;
        uint256 until;
        bool active;
    }

    // Mapping from a unique lock ID to the Lock struct.
    mapping(uint256 => Lock) public locks;

    // Counter to generate unique lock IDs. Starts at 1.
    uint256 private _lockIdCounter;

    /**
     * @dev Emitted when funds are locked.
     * @param id The unique ID of the lock.
     * @param owner The address of the user who locked the funds.
     * @param amount The amount of Ether locked.
     * @param until The timestamp until which the funds are locked.
     */
    event Locked(uint256 id, address indexed owner, uint256 amount, uint256 until);

    /**
     * @dev Emitted when funds are unlocked.
     * @param id The unique ID of the lock being unlocked.
     * @param owner The address of the user who owned the lock.
     * @param amount The amount of Ether unlocked.
     */
    event Unlocked(uint256 id, address indexed owner, uint256 amount);

    /**
     * @dev The constructor is intentionally left empty as per requirements.
     * State variables are initialized to their default values (e.g., _lockIdCounter starts at 0).
     */
    constructor() {
        // Empty constructor
    }

    /**
     * @notice Locks a specified amount of Ether until a given timestamp.
     * @dev The `amount` parameter must match `msg.value`. The `until` timestamp must be in the future.
     * A unique lock ID is generated and associated with the sender's lock information.
     * @param amount The amount of Ether to lock, in wei.
     * @param until The UNIX timestamp (seconds) until which the funds will be locked.
     */
    function lock(uint256 amount, uint256 until) external payable {
        require(msg.value == amount, "Timelock: Sent Ether value must match the lock amount");
        require(amount > 0, "Timelock: Lock amount must be greater than zero");
        require(until > block.timestamp, "Timelock: Lock duration must be in the future");

        uint256 id = ++_lockIdCounter;
        locks[id] = Lock({
            owner: msg.sender,
            amount: amount,
            until: until,
            active: true
        });

        emit Locked(id, msg.sender, amount, until);
    }

    /**
     * @notice Unlocks a specific lock by its ID, transferring the Ether back to the owner.
     * @dev Can only be called by the owner of the lock.
     * The lock must be active and the lock period must have expired.
     * This function is protected against re-entrancy attacks.
     * @param id The ID of the lock to unlock.
     */
    function unlock(uint256 id) external nonReentrant {
        Lock storage locked = locks[id];

        require(locked.active, "Timelock: Lock is not active or does not exist");
        require(locked.owner == msg.sender, "Timelock: Caller is not the owner of the lock");
        require(block.timestamp >= locked.until, "Timelock: Lock period has not expired");

        // Checks-Effects-Interactions pattern: update state before external call
        uint256 amountToUnlock = locked.amount;
        locked.active = false;

        // Send the locked Ether back to the owner
        (bool success, ) = msg.sender.call{value: amountToUnlock}("");
        require(success, "Timelock: ETH transfer failed");

        emit Unlocked(id, msg.sender, amountToUnlock);
    }
}
