/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title TokenMinter
 * @author Expert Solidity Engineer
 * @notice A secure ERC20 token contract with minting capabilities restricted to the owner.
 * @dev This contract uses OpenZeppelin v4.9.x for its ERC20 and Ownable implementations.
 * The token name is 'MinterToken' and the symbol is 'MINT', which are hard-coded.
 * The contract is initialized with an empty constructor, and ownership is set
 * to the deployer's address.
 */
contract TokenMinter is ERC20, Ownable {

    /**
     * @dev Emitted when tokens are minted.
     * @param to The recipient address of the newly minted tokens.
     * @param amount The quantity of tokens minted.
     */
    event Minted(address indexed to, uint256 amount);

    /**
     * @dev Initializes the ERC20 token with a fixed name and symbol.
     * The constructor is empty as it accepts no arguments. The deployer
     * of the contract is automatically set as the owner via the Ownable constructor.
     */
    constructor() ERC20("MinterToken", "MINT") {
        // The body of the constructor is intentionally left empty.
        // The Ownable constructor is implicitly called, setting msg.sender as the owner.
    }

    /**
     * @notice Creates `amount` tokens and assigns them to the `to` address.
     * @dev This function is restricted to the contract owner. It increases the
     * total supply of the token. Emits a {Minted} event upon successful execution.
     * @param to The address that will receive the minted tokens.
     * @param amount The amount of tokens to mint.
     */
    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
        emit Minted(to, amount);
    }
}
