/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title TokenFaucet
 * @author The Solidity Expert
 * @notice A faucet contract to distribute a specific ERC20 token to users.
 * @dev This contract allows an owner to set an ERC20 token and drip a
 * configured amount to users, subject to a cooldown period. The owner must
 * fund the contract with the specified ERC20 token. The contract is initialized
 * without a token and must be configured by the owner after deployment.
 */
contract TokenFaucet is Ownable {
    using SafeERC20 for IERC20;

    /**
     * @notice The ERC20 token this faucet dispenses.
     */
    IERC20 public token;

    /**
     * @notice The amount of tokens to dispense in each drip.
     */
    uint256 public dripAmount;

    /**
     * @notice The cooldown period in seconds between drips for a single user.
     */
    uint256 public dripCooldown;

    /**
     * @dev Mapping to store the last time a user received a drip.
     * The value is a timestamp.
     */
    mapping(address => uint256) public lastDripped;

    /**
     * @dev Emitted when the faucet's token is set or changed.
     * @param token The address of the new ERC20 token.
     */
    event TokenSet(address indexed token);

    /**
     * @dev Emitted when a user receives tokens from the faucet.
     * @param user The address of the recipient.
     * @param amount The amount of tokens dripped.
     */
    event Dripped(address indexed user, uint256 amount);

    /**
     * @dev The constructor is empty as per requirements. Ownership is
     * implicitly transferred to the deployer by the Ownable constructor.
     */
    constructor() {}

    /**
     * @notice Sets the ERC20 token to be dispensed by the faucet.
     * @dev Can only be called by the owner. The token address cannot be the zero address.
     * @param tokenAddress The address of the ERC20 token contract.
     */
    function setToken(address tokenAddress) public onlyOwner {
        require(tokenAddress != address(0), "TokenFaucet: Token address cannot be zero");
        token = IERC20(tokenAddress);
        emit TokenSet(tokenAddress);
    }

    /**
     * @notice Sets the amount of tokens to be dispensed in each drip.
     * @dev Can only be called by the owner.
     * @param amount The new amount for each drip.
     */
    function setDripAmount(uint256 amount) public onlyOwner {
        dripAmount = amount;
    }

    /**
     * @notice Sets the cooldown period between drips for a single user.
     * @dev Can only be called by the owner.
     * @param cooldown The new cooldown period in seconds.
     */
    function setDripCooldown(uint256 cooldown) public onlyOwner {
        dripCooldown = cooldown;
    }

    /**
     * @notice Dispenses tokens to a specified user.
     * @dev The faucet must be configured with a token and a non-zero drip amount.
     * The calling user must not be on cooldown.
     * The faucet must have sufficient token balance.
     * @param user The address of the recipient.
     */
    function drip(address user) public {
        require(address(token) != address(0), "TokenFaucet: Token not set");
        require(user != address(0), "TokenFaucet: Cannot drip to zero address");
        require(dripAmount > 0, "TokenFaucet: Drip amount not set");
        require(block.timestamp >= lastDripped[user] + dripCooldown, "TokenFaucet: Cooldown active");
        require(token.balanceOf(address(this)) >= dripAmount, "TokenFaucet: Faucet is empty");

        lastDripped[user] = block.timestamp;

        token.safeTransfer(user, dripAmount);

        emit Dripped(user, dripAmount);
    }

    /**
     * @notice Allows the owner to withdraw the entire balance of the configured token.
     * @dev This is useful for decommissioning the faucet or retrieving excess funds.
     * Can only be called by the owner.
     */
    function withdraw() public onlyOwner {
        require(address(token) != address(0), "TokenFaucet: Token not set");
        uint256 balance = token.balanceOf(address(this));
        require(balance > 0, "TokenFaucet: No tokens to withdraw");
        token.safeTransfer(owner(), balance);
    }
}
