/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title Vault
 * @dev A simple contract where users can deposit and withdraw Ether securely.
 * This vault tracks individual user balances, allowing each user to withdraw
 * only the amount they have deposited. It uses OpenZeppelin's ReentrancyGuard
 * to prevent re-entrancy attacks during withdrawals.
 */
contract Vault is ReentrancyGuard {
    // Mapping from user address to their balance in the vault.
    mapping(address => uint256) private _balances;

    /**
     * @dev Emitted when a user deposits Ether.
     * @param user The address of the depositor.
     * @param amount The amount of Ether deposited.
     */
    event Deposited(address indexed user, uint256 amount);

    /**
     * @dev Emitted when a user withdraws Ether.
     * @param user The address of the recipient.
     * @param amount The amount of Ether withdrawn.
     */
    event Withdrawn(address indexed user, uint256 amount);

    /**
     * @dev The constructor is empty as required.
     */
    constructor() {}

    /**
     * @dev Allows a user to deposit Ether into the vault.
     * The deposited amount is added to the user's balance.
     * Emits a {Deposited} event.
     *
     * Requirements:
     * - The value sent with the transaction must be greater than 0.
     */
    function deposit() external payable nonReentrant {
        uint256 amount = msg.value;
        require(amount > 0, "Vault: Deposit amount must be greater than 0");

        _balances[msg.sender] += amount;

        emit Deposited(msg.sender, amount);
    }

    /**
     * @dev Allows a user to withdraw a specified amount of Ether from their balance.
     * Follows the Checks-Effects-Interactions pattern to prevent re-entrancy.
     * Emits a {Withdrawn} event.
     *
     * Requirements:
     * - The `amount` to withdraw must be greater than 0.
     * - The user must have a balance sufficient to cover the withdrawal amount.
     * - The ETH transfer must succeed.
     *
     * @param amount The amount of Ether to withdraw in Wei.
     */
    function withdraw(uint256 amount) external nonReentrant {
        require(amount > 0, "Vault: Withdraw amount must be greater than 0");

        uint256 userBalance = _balances[msg.sender];
        require(userBalance >= amount, "Vault: Insufficient balance");

        // Effects: Update state before interaction
        _balances[msg.sender] = userBalance - amount;

        emit Withdrawn(msg.sender, amount);

        // Interaction: Send the Ether
        (bool success, ) = msg.sender.call{value: amount}("");
        require(success, "Vault: ETH transfer failed");
    }

    /**
     * @dev Returns the balance of a specific account.
     * @param account The address of the account to query.
     * @return The balance of the account in Wei.
     */
    function balanceOf(address account) external view returns (uint256) {
        return _balances[account];
    }

    /**
     * @dev Returns the total balance of Ether held by this contract.
     * @return The total balance in Wei.
     */
    function totalBalance() external view returns (uint256) {
        return address(this).balance;
    }
}
