/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

/**
 * @title VotingBooth
 * @dev A simple contract for creating and voting on proposals.
 *
 * This contract allows any user to:
 * 1. Propose a new item for voting.
 * 2. Cast a vote (for or against) on an open proposal.
 * 3. Close a proposal, finalizing the vote count.
 *
 * It ensures that each user can only vote once per proposal.
 */
contract VotingBooth {

    // --- State Variables ---

    struct Proposal {
        uint256 id;
        address proposer;
        string description;
        uint256 forVotes;
        uint256 againstVotes;
        bool isOpen;
    }

    // Mapping from proposal ID to Proposal struct.
    mapping(uint256 => Proposal) public proposals;

    // Mapping from proposal ID to voter address to check if they have voted.
    mapping(uint256 => mapping(address => bool)) public hasVoted;

    // Counter for new proposal IDs.
    uint256 private _nextProposalId;

    // --- Events ---

    /**
     * @dev Emitted when a new proposal is created.
     * @param id The unique ID of the proposal.
     * @param proposer The address that created the proposal.
     * @param description The text of the proposal.
     */
    event Proposed(uint256 indexed id, address indexed proposer, string description);

    /**
     * @dev Emitted when a vote is cast on a proposal.
     * @param id The ID of the proposal being voted on.
     * @param voter The address of the voter.
     * @param support The voter's choice (true for 'for', false for 'against').
     */
    event Voted(uint256 indexed id, address indexed voter, bool support);

    /**
     * @dev Emitted when a proposal is closed.
     * @param id The ID of the closed proposal.
     * @param forVotes The final count of 'for' votes.
     * @param againstVotes The final count of 'against' votes.
     */
    event Closed(uint256 indexed id, uint256 forVotes, uint256 againstVotes);


    // --- Constructor ---

    /**
     * @dev The constructor is empty as per the requirements.
     * Proposal IDs start from 0.
     */
    constructor() {
        // _nextProposalId is initialized to 0 by default.
    }

    // --- Public Functions ---

    /**
     * @notice Creates a new proposal.
     * @dev Creates a new proposal with a unique ID and sets the caller as the proposer.
     * @param desc The description of the proposal.
     * @return id The ID of the newly created proposal.
     */
    function propose(string memory desc) public returns (uint256 id) {
        id = _nextProposalId;

        proposals[id] = Proposal({
            id: id,
            proposer: msg.sender,
            description: desc,
            forVotes: 0,
            againstVotes: 0,
            isOpen: true
        });

        _nextProposalId++;

        emit Proposed(id, msg.sender, desc);
    }

    /**
     * @notice Casts a vote on an open proposal.
     * @dev Allows a user to vote 'for' (support = true) or 'against' (support = false).
     * Reverts if the proposal does not exist, is not open, or if the user has already voted.
     * @param id The ID of the proposal to vote on.
     * @param support The voter's decision (true for 'for', false for 'against').
     */
    function vote(uint256 id, bool support) public {
        Proposal storage p = proposals[id];

        // Check if the proposal exists. A non-existent proposal will have a zero address proposer.
        require(p.proposer != address(0), "VotingBooth: proposal does not exist");
        require(p.isOpen, "VotingBooth: proposal is not open");
        require(!hasVoted[id][msg.sender], "VotingBooth: already voted");

        hasVoted[id][msg.sender] = true;

        if (support) {
            p.forVotes++;
        } else {
            p.againstVotes++;
        }

        emit Voted(id, msg.sender, support);
    }

    /**
     * @notice Closes an open proposal, preventing further votes.
     * @dev Can be called by anyone. Finalizes the vote count.
     * Reverts if the proposal does not exist or is already closed.
     * @param id The ID of the proposal to close.
     */
    function close(uint256 id) public {
        Proposal storage p = proposals[id];

        require(p.proposer != address(0), "VotingBooth: proposal does not exist");
        require(p.isOpen, "VotingBooth: proposal is not open");

        p.isOpen = false;

        emit Closed(id, p.forVotes, p.againstVotes);
    }
}
