/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title Whitelist
 * @dev Manages a list of whitelisted addresses.
 * The contract owner has the authority to add and remove addresses from the whitelist.
 * This contract is designed to be simple, secure, and gas-efficient for checking
 * whitelist status.
 */
contract Whitelist is Ownable {
    /**
     * @dev Mapping from an address to its whitelisted status.
     */
    mapping(address => bool) private _whitelisted;

    /**
     * @dev Emitted when a new account is added to the whitelist.
     */
    event Added(address indexed account);

    /**
     * @dev Emitted when an account is removed from the whitelist.
     */
    event Removed(address indexed account);

    /**
     * @dev The constructor is empty, and the deployer is automatically set as the
     * owner by the Ownable constructor.
     */
    constructor() {
        // The deployer is automatically set as the owner.
    }

    /**
     * @dev Adds a new address to the whitelist.
     * Can only be called by the owner.
     * @param account The address to add to the whitelist.
     */
    function add(address account) public onlyOwner {
        require(account != address(0), "Whitelist: cannot add the zero address");
        require(!_whitelisted[account], "Whitelist: account already added");

        _whitelisted[account] = true;
        emit Added(account);
    }

    /**
     * @dev Removes an address from the whitelist.
     * Can only be called by the owner.
     * @param account The address to remove from the whitelist.
     */
    function remove(address account) public onlyOwner {
        require(account != address(0), "Whitelist: cannot remove the zero address");
        require(_whitelisted[account], "Whitelist: account not on the list");

        _whitelisted[account] = false;
        emit Removed(account);
    }

    /**
     * @dev Checks if an address is on the whitelist.
     * @param account The address to check.
     * @return bool True if the address is whitelisted, false otherwise.
     */
    function check(address account) public view returns (bool) {
        return _whitelisted[account];
    }
}
