import { NextResponse } from 'next/server';

/*
===============================================================================
 DEMO API ROUTE (Mock)
-------------------------------------------------------------------------------
 This returns a static sample Solidity source for UI demonstrations only.
 It does not reflect the production artifacts API documented in docs/AI_Deployment_API.md.
 The main pipeline UI now uses lib/api.ts to call the real backend; this mock
 remains only for sandboxing and local demos.
===============================================================================
*/

export async function GET(
  request: Request,
  { params }: { params: { jobId: string } }
) {
  try {
    const { jobId } = params;
    
    if (!jobId) {
      return NextResponse.json(
        { error: 'Job ID is required' },
        { status: 400 }
      );
    }

    // TODO: In a real implementation, you would:
    // 1. Look up the job in your database
    // 2. Verify the job is in a 'ready' or 'completed' state
    // 3. Return the generated source code
    
    // Sample Solidity contract - in a real app, this would come from your AI service
    const sampleContract = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title SampleGeneratedContract
 * @dev This contract was generated by Camp Codegen AI
 */
contract SampleGeneratedContract {
    address public owner;
    string public greeting;

    event GreetingChanged(string newGreeting);

    constructor(string memory _greeting) {
        owner = msg.sender;
        greeting = _greeting;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Only the contract owner can call this function");
        _;
    }

    function setGreeting(string memory _greeting) public onlyOwner {
        greeting = _greeting;
        emit GreetingChanged(_greeting);
    }

    function getGreeting() public view returns (string memory) {
        return greeting;
    }
}`;

    return NextResponse.json({
      jobId,
      sourceCode: sampleContract,
      language: 'solidity',
      filename: 'GeneratedContract.sol'
    });

  } catch (error) {
    console.error('Error fetching source code:', error);
    return NextResponse.json(
      { error: 'Failed to fetch contract source' },
      { status: 500 }
    );
  }
}
