/**
 * This smart contract is generated by Camp-Codegen
 * Build by www.blockxint.com
 * Feel free to reach out at mohit@blockxint.com for queries
 */
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title MarketChannelProxy
 * @dev A multi-purpose contract that combines ERC721 NFT minting with an
 * ERC20 token locking mechanism and a hash commitment feature.
 *
 * The contract allows a designated owner to mint unique NFTs (ERC721).
 * Users can lock a specified ERC20 token for a chosen duration. After the
 * lock period, they can unstake their tokens. The contract also includes a
 * function for users to commit a hash, which can be used for various
 * on-chain or off-chain protocols.
 *
 * This contract uses OpenZeppelin v4.9.x for secure, standard implementations of
 * ERC721, Ownable, and ReentrancyGuard. It is designed to be deployed with an
 * empty constructor. The staking token must be set by the owner after deployment.
 */
contract MarketChannelProxy is Ownable, ERC721, ERC721URIStorage, ReentrancyGuard {
    // --- Custom Errors ---

    error StakingTokenNotSet();
    error AmountIsZero();
    error DurationIsZero();
    error ExistingLockFound();
    error TokenTransferFailed();
    error InsufficientLockedAmount();
    error LockupPeriodNotEnded();
    error HashAlreadyCommitted();
    error ZeroAddress();

    // --- State Variables ---

    /**
     * @dev The ERC20 token used for locking.
     */
    IERC20 public stakingToken;

    /**
     * @dev Represents the lock information for a user.
     * @param amount The total amount of tokens locked.
     * @param unlockTime The Unix timestamp after which tokens can be withdrawn.
     */
    struct LockInfo {
        uint256 amount;
        uint256 unlockTime;
    }

    /**
     * @dev Maps a user's address to their token lock information.
     */
    mapping(address => LockInfo) public userLocks;

    /**
     * @dev Maps a hash to a boolean indicating if it has been committed.
     */
    mapping(bytes32 => bool) public commitments;

    // --- Events ---

    /**
     * @dev Emitted when a new NFT is minted.
     * @param to The address receiving the NFT.
     * @param tokenId The unique ID of the minted NFT.
     */
    event Minted(address indexed to, uint256 indexed tokenId);

    /**
     * @dev Emitted when a user locks tokens.
     * @param user The address of the user locking tokens.
     * @param amount The amount of tokens locked.
     * @param unlockTime The timestamp when the tokens can be unstaked.
     */
    event TokensLocked(address indexed user, uint256 amount, uint256 unlockTime);
    
    /**
     * @dev Emitted when a user unstakes tokens.
     * @param user The address of the user unstaking tokens.
     * @param amount The amount of tokens unstaked.
     */
    event TokensUnstaked(address indexed user, uint256 amount);

    /**
     * @dev Emitted when a hash is committed.
     * @param committer The address committing the hash.
     * @param hash The committed hash.
     */
    event Committed(address indexed committer, bytes32 indexed hash);


    // --- Constructor ---

    /**
     * @dev Initializes the contract, setting the NFT name and symbol.
     * The constructor body is empty as per requirements.
     */
    constructor() ERC721("MarketChannelNFT", "MCN") {
        // This constructor is intentionally empty.
        // The owner must configure the staking token via setStakingToken().
    }

    // --- Owner-only Functions ---

    /**
     * @dev Sets the address of the ERC20 token to be used for locking.
     * Can only be called by the contract owner.
     * @param tokenAddress The address of the ERC20 staking token.
     */
    function setStakingToken(address tokenAddress) external onlyOwner {
        if (tokenAddress == address(0)) revert ZeroAddress();
        stakingToken = IERC20(tokenAddress);
    }
    
    /**
     * @dev Mints a new NFT and assigns it to an address.
     * Requires the caller to be the owner. Emits a {Minted} event.
     * @param to The address to mint the NFT to.
     * @param tokenId The ID of the new token.
     */
    function mintNFT(address to, uint256 tokenId) external onlyOwner {
        _safeMint(to, tokenId);
        emit Minted(to, tokenId);
    }

    /**
     * @dev Sets the URI for a given token ID.
     * The URI is a link to a JSON file that conforms to the "ERC721 Metadata JSON Schema".
     * Requires the caller to be the owner.
     * @param tokenId The ID of the token.
     * @param uri The URI for the token's metadata.
     */
    function setTokenURI(uint256 tokenId, string calldata uri) external onlyOwner {
        _setTokenURI(tokenId, uri);
    }

    // --- Public Functions ---

    /**
     * @dev Locks a specified amount of staking tokens for a given duration.
     * The user must first approve this contract to spend their tokens.
     * A user cannot lock new tokens if they have an existing, non-zero lock.
     * @param amount The amount of staking tokens to lock.
     * @param duration The duration in seconds for which to lock the tokens.
     */
    function lockTokens(uint256 amount, uint256 duration) external nonReentrant {
        if (address(stakingToken) == address(0)) revert StakingTokenNotSet();
        if (amount == 0) revert AmountIsZero();
        if (duration == 0) revert DurationIsZero();
        if (userLocks[msg.sender].amount > 0) revert ExistingLockFound();

        uint256 unlockTime = block.timestamp + duration;
        
        // Effects before Interactions: Update the user's lock state.
        userLocks[msg.sender] = LockInfo(amount, unlockTime);

        // Interaction: Pull tokens from the user.
        // If transferFrom fails (e.g., returns false), the revert will undo the state change above.
        if (!stakingToken.transferFrom(msg.sender, address(this), amount)) {
            revert TokenTransferFailed();
        }

        emit TokensLocked(msg.sender, amount, unlockTime);
    }

    /**
     * @dev Unstakes a specified amount of locked tokens.
     * The lock duration must have passed.
     * @param amount The amount of staking tokens to unstake.
     */
    function unstake(uint256 amount) external nonReentrant {
        LockInfo storage lock = userLocks[msg.sender];
        
        if (amount == 0) revert AmountIsZero();
        if (lock.amount < amount) revert InsufficientLockedAmount();
        if (block.timestamp < lock.unlockTime) revert LockupPeriodNotEnded();

        // Effects before Interactions: Decrease the locked amount.
        lock.amount -= amount;

        // Interaction: Send tokens back to the user.
        // If transfer fails (e.g., returns false), the revert will undo the state change above.
        if (!stakingToken.transfer(msg.sender, amount)) {
            revert TokenTransferFailed();
        }

        emit TokensUnstaked(msg.sender, amount);
    }
    
    /**
     * @dev Commits a hash to the contract state.
     * Prevents the same hash from being committed twice.
     * @param hash The bytes32 hash to commit.
     */
    function commit(bytes32 hash) external {
        if (commitments[hash]) revert HashAlreadyCommitted();
        commitments[hash] = true;
        emit Committed(msg.sender, hash);
    }

    // --- Overrides ---

    /**
     * @dev See {ERC721-_burn}.
     * Required for compatibility with ERC721URIStorage.
     */
    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }

    /**
     * @dev See {ERC721URIStorage-tokenURI}.
     */
    function tokenURI(uint256 tokenId) public view override(ERC721, ERC721URIStorage) returns (string memory) {
        return super.tokenURI(tokenId);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721URIStorage) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}
